### ISSUE TITLE
Alignment issues on React Native in List with Icons

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#1023]
ListWithIcons story for List component seem to have some alignment issues on React Native

<img width="305" alt="image" src="https://user-images.githubusercontent.com/30949385/220911426-0091e182-2865-4719-bc9b-7e8118313851.png">

**Comment by chaitanyadeorukhkar** [comment]
This is related to an issue with Link not related to List or Icons. Ref: https://github.com/razorpay/blade/issues/972

**Comment by saurabhdaware** [comment]
Oh cool. we can close this then and discuss on #972
