### ISSUE TITLE
All Icons story is breaking in React Native

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#1027]
The All Icons story from storybook is breaking on react native with several platform specific issues.

**Comment by divyanshu013** [comment]
There's an [icon gallery block](https://storybook.js.org/docs/react/api/doc-block-icongallery) which might work here, need to be verified if it works on native though.

**Comment by saurabhdaware** [comment]
I think icon gallery is not available in current storybook version. We'll have to upgrade storybook before that.

**Comment by divyanshu013** [comment]
Alternatively, meanwhile, might need to fix the native storybook 🥲

**Comment by anuraghazra** [comment]
Closing this for now as this may not be relevant anymore with all the changes (rebranding,storybook upgrade) we did. 

Will open new issue if any RN related setup found broken.

**Comment by abhinav2196** [comment]
Hi can someone please tell me how to unsubscribe from this thread?

**Comment by abhinav2196** [comment]
I am not wtaching this repository but still receiving the notifications, it is a lot of noise
