### ISSUE TITLE
Read release and some other information from ComponentStatus files and add it to storybook page wrapper

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#1030]
There's lots of information available now in ComponentStatus file. We can import that info object in StoryPageWrapper and add it in header of each story.

**Comment by kamleshchandnani** [comment]
what do we intend to solve with this?

**Comment by saurabhdaware** [comment]
When people land on documentation of particular component, they will know which minimum version they need to upgrade to to use that component.

Will just save few clicks of going through component status page
