### ISSUE TITLE
Web file imported in native

### ISSUE THREAD

**Issue by chaitanyadeorukhkar** [razorpay/blade#1033]
https://github.com/razorpay/blade/blob/c994b0e7e827d8734d2e1d6b62c708bb1121e22b/packages/blade/src/components/Dropdown/DropdownOverlay.native.tsx#L5

Since we're only importing a type, it's not breaking anything but we should avoid importing from `.web` files to a `.native` file

**Comment by chaitanyadeorukhkar** [comment]
@saurabhdaware can you check this whenever possible?

**Comment by divyanshu013** [comment]
We should add a linting rule for this

**Comment by saurabhdaware** [comment]
yeah sure I'll check
