### ISSUE TITLE
IconButton is not properly visible on dark mode

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#1084]
<img width="402" alt="image" src="https://user-images.githubusercontent.com/30949385/226599237-8764bd90-01a1-4799-b74f-020e933f3ebb.png">

The color of IconButton seems to stay same on dark and light mode. 

https://blade.razorpay.com/?path=/docs/components-iconbutton--icon-button

**Comment by saurabhdaware** [comment]
Heya @Vishruta-Patil, thanks for showing interest. But we're yet to discuss and rethink this from design side which might take some time so we're not yet sure what is the right fix for this. I can update on this issue when we discuss

**Comment by saurabhdaware** [comment]
For Reference: This is something that came up in our BottomSheet implementation as well (we might need to have back button and close button in white color there). Might have to prioritise and standardise this in tokens-side.

**Comment by divyanshu013** [comment]
@anuraghazra to check against bottom sheet and update if we need this

**Comment by saurabhdaware** [comment]
This got fixed with rebranding in our new color tokens
