### ISSUE TITLE
Upgrade to new rollup version

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#1087]
Can't we upgrade our rollup version and use this?

_Originally posted by @chaitanyadeorukhkar in https://github.com/razorpay/blade/pull/1045#discussion_r1143179398_
            
We would be able to remove custom babel plugin of manualPureFunction with it.

TODO:
- Check new features that it offers
- Check breaking changes
- Upgrade

**Comment by saurabhdaware** [comment]
> Any specific version we are targeting.

We are looking to move to latest version

> Any specific feature we are looking at after upgrade

One particular we're looking for is -
- https://rollupjs.org/configuration-options/#treeshake-manualpurefunctions (we currently have custom babel plugin)

I think rest are the things we can pick one-by-one when usecase comes and that feature is required. Currently we can just focus to migrate and fix breaking changes.

**Comment by saurabhdaware** [comment]
awesome! thanks 👯 Let us know if you need some help.

**Comment by kamleshchandnani** [comment]
@loombarishav do you have an ETA to finish this?

**Comment by loombarishav** [comment]
I picked this task in Q1 S4 sprint, but due to some P0 feature delivery (3 weeks work), I moved this to backlog. And after that i forgot to pick this task again. My bad. 
Surely Will pick and complete this in next sprint (Already packed heavily in this sprint).
@kamleshchandnani

**Comment by snitin315** [comment]
@saurabhdaware I tried this new option but it doesn't seem to be working as expected. I see size-limit crossing if I remove the babel-plugin and use this option.

<img width="632" alt="Screenshot 2023-09-04 at 8 45 56 AM" src="https://github.com/razorpay/blade/assets/46647141/bab818f1-42d2-4821-8159-4e8c4dc68501">

<img width="761" alt="Screenshot 2023-09-04 at 8 44 30 AM" src="https://github.com/razorpay/blade/assets/46647141/b49327a9-02d1-42cc-a4ce-e710dbe69420">

**Comment by anuraghazra** [comment]
Done as part of #1563
