### ISSUE TITLE
Change instances of `JSX.Element` to `React.ReactElement`

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#1089]
I've been adding `JSX.Element` return type everywhere in my components lol. We need to change that to `React.ReactElement` during next major release.

Won't be any critical breaking change but we can do it during major release in case someone has written some typecheck code somewhere.

**Comment by saurabhdaware** [comment]
Update: we decided to do this without breaking change

**Comment by chaitanyadeorukhkar** [comment]
@saurabhdaware why was this marked as a P0? is this having any direct impact on the consumers?

**Comment by saurabhdaware** [comment]
Nope. low effort tasks were marked as P0s

**Comment by snitin315** [comment]
@saurabhdaware So we need to update [all the instances of `JSX.Element`](https://github.com/search?q=repo%3Arazorpay%2Fblade%20JSX.Element&type=code)?
