### ISSUE TITLE
Card's subtitle overlaps with trailing badge component when the subtitle is longer on React Native

### ISSUE THREAD

**Issue by chaitanyadeorukhkar** [razorpay/blade#1091]
Badge being used inside Card title with a longer subtitle is causing a visual issue

![simulator_screenshot_FC6C58AA-9045-40C5-950F-29B9B806CB8B](https://user-images.githubusercontent.com/24487274/228147168-b38d1e98-13b5-4564-a4de-a54bebf214c7.png)

**Comment by PratishShrivastava** [comment]
@chaitanyadeorukhkar can i take this issue if no one is working on this.
