### ISSUE TITLE
Regenerate icons to ensure SVG paths are not optimized

### ISSUE THREAD

**Issue by anuraghazra** [razorpay/blade#1098]
Found a bug in #1096 where the SVG paths were optimized by the generator script which causes the alignment issue. 

Slack Thread: https://razorpay.slack.com/archives/C035U5CGB0F/p1680002850557459

TODO: Regenerate and double check if any icons are breaking or not

**Comment by divyanshu013** [comment]
Todo
- Also add the script

**Comment by kamleshchandnani** [comment]
@anuraghazra if you get time can you fix this? low hanging

**Comment by anuraghazra** [comment]
This is done as part of #2164
