### ISSUE TITLE
Document utilities in blade

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#1101]
we don't document our utilities that are exposed from blade documented anywhere. Will be better to document usage and usecases somewhere

**Comment by nashcheez** [comment]
Relevant [thread & request](https://razorpay.slack.com/archives/CMQ3RBHEU/p1680505182215379).

**Comment by divyanshu013** [comment]
Also to consider the utlis we want consumers to use eg. spacing, responsive (media queries), theme, etc.

**Comment by saurabhdaware** [comment]
We should do this before writing documentation - https://github.com/razorpay/blade/issues/1136

We'll have to move few utils to internal utils and not expose them to consumer. Currently it's a bit mixed.
