### ISSUE TITLE
Adding typescript check for default props

### ISSUE THREAD

**Issue by kkyusufk** [razorpay/blade#1117]
### Problem
I have seen multiple PR's where devs write the components like this
```
const SampleComponent = () => {
  return <Heading size="small" variant="regular" weight ="bold" contrast="low"> Hello Blade! </Heading>
}
```
devs are passing the props with the default values. This makes the code un-necessarily long and defeats the purpose of default values for props.

### Solution
Add a check to make sure that devs do not pass default props. 
This would immediately give them feedback and make sure this is caught in development rather than PR review.

**Comment by snitin315** [comment]
I feel it's fine to explicitly mention a prop's value even if it's the default one. Defaults can change anytime.

**Comment by kkyusufk** [comment]
Yes, it's totally fine. The suggestion was a minor enhancement to educate folks that they do not need to pass these props un necessarily.

**Comment by saurabhdaware** [comment]
Agree with Nitin and Anurag. Also, A bit difficult to implement on TypeScript end for every prop. 

Will close this issue for now but let me know if something is unanswered. Can reopen for discussion if multiple consumers request this.
