### ISSUE TITLE
Add a semver note in documentation

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#1155]
We don't exactly follow the traditional semantic versioning. We consider change as a breaking change only when significant usage is found in razorpay repositories. Ideally we should have a clear note on how we do versioning so that people don't get confused.

**Comment by divyanshu013** [comment]
We do keep things close to semver :) I think it should be fine to not add a note explicitly, all changes are documented in the changelog. For breaking things we do add warnings:

> **Warning**
>
> This has changed

**Comment by saurabhdaware** [comment]
That is true. My concern is someone might ignore the changelogs of minor upgrades and jump between major upgrade changelogs only while upgrading. But yes we can take a relook at adding note if we face any issues with this approach
