### ISSUE TITLE
Add support for xsmall size in Link. 

### ISSUE THREAD

**Issue by sumit-gupta91** [razorpay/blade#1162]
Currently Blade offers a way to render Link in line with a Text. Text offers a xsmall variant but Link does not offers a small variant and things look out of place. 
Have a look at this snapshot. Text is xsmall and type is subdued.
<img width="348" alt="Screenshot 2023-05-09 at 11 17 19 AM" src="https://user-images.githubusercontent.com/6623629/237005269-af674637-bae2-485b-94a8-19a3e9c7e16d.png">

Should we expose a subdued property on Link as well ? 
I am trying to migrate below snapshot to Blade and there is no way currently for Link to look same.
<img width="350" alt="Screenshot 2023-05-09 at 11 18 44 AM" src="https://user-images.githubusercontent.com/6623629/237005637-b6f8eb30-971a-45bd-bce5-f6e011d8b6b2.png">

**Comment by saurav12** [comment]
What if we just expose a `xsmall` variant on a `Link` component itself?
// @kamleshchandnani

**Comment by kamleshchandnani** [comment]
We did plan the Link `xsmall` when we were redoing typography scales. @anuraghazra can add more.

@sumit-gupta91 for the subdued thing, not planning right now it has more nuances like active and hover states so we've this in backlog but not prioritised right now. in this current use case ideally it shall be blue only given the context.

**Comment by sumit-gupta91** [comment]
Done, will share same with design that subdued or light variant of link will not be exposed. 
Though xsmall size might be added.

**Comment by saurav12** [comment]
Will need to take this up on my side and get it added to the main component itself.

**Comment by divyanshu013** [comment]
We can take it up on dev once it's available on design

**Comment by chaitanyadeorukhkar** [comment]
This is available on design now. We can take this up
