### ISSUE TITLE
Button: Support rendering as anchor tag with href

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#1166]
We currently don't have a way where we can pass `href` to our Button component. Ideal API in my opinion would be where consumers can pass `href` prop and based on that, we render the button as anchor tag with that href.

```jsx
<Button href="/signup">Sign Up</Button> // renders as `<a href="/signup">Sign Up</a>`
```

## Original Request

              No, it doesn't matter which variant of button is used. The button component in blade doesn't support `to` or `href` attribute. My question is how do I redirect to another page using button component from blade (Is `onClick` the only option here?)

@saurabhdaware @divyanshu013

_Originally posted by @Kushagra-ag in https://github.com/razorpay/blade/issues/1165#issuecomment-1543885548_

**Comment by chaitanyadeorukhkar** [comment]
Is this a valid HTML behaviour? Natively HTML doesn't transform a <button> to <a> is we pass href

**Comment by saurabhdaware** [comment]
No I meant we can handle it on our end. something like - `props.href ? <BaseLink /> : <BaseButton />`

**Comment by kamleshchandnani** [comment]
But we'll need to make BaseLink to also look like button in this case right?

**Comment by saurabhdaware** [comment]
yes. styles can be moved to separate file so it will be `styled(BaseLink)(() => buttonStyles())`, `styled(BaseButton)(() => buttonStyles())`

**Comment by saurabhdaware** [comment]
oh actually no. We can just not touch BaseLink at all and just change the render item of BaseButton. It will be `a` on web and `Link` in react native

**Comment by chaitanyadeorukhkar** [comment]
I'm still not sure what we're trying to achieve here. Why can't we use `onClick` instead?

**Comment by divyanshu013** [comment]
Semantically should be rendered as `a` tag (with `href`) (also has SEO impact)
