### ISSUE TITLE
Border support in Blade (Box)

### ISSUE THREAD

**Issue by neeraj719714** [razorpay/blade#1181]
## Description
Most of the designs we use require a border in them. Currently it's not supported here in blade.
We currently have to rely on custom made wrappers for this.

Would be great if we can add this to `Box`.

**Comment by chaitanyadeorukhkar** [comment]
Can you also add the figma link and screenshot on the issue? Would be helpful for future reference

**Comment by kamleshchandnani** [comment]
@neeraj719714 Can you share some of those screenshots? we need to evaluate whether these are legitimate `Box` use cases or `Card` cases?

**Comment by neeraj719714** [comment]
## screenshot

<img width="921" alt="Screenshot 2023-05-19 at 3 14 57 PM" src="https://github.com/razorpay/blade/assets/24440859/9c7eab28-a024-40ce-a86d-be6146e4c620">
