### ISSUE TITLE
Floating Menu Items for Dropdown component

### ISSUE THREAD

**Issue by prabhasjoshi** [razorpay/blade#1207]
**Problem**

Currently in the newly released dropdown component 
[https://61c19ee8d3d282003ac1d81c-jiyhlozugn.chromatic.com/?path=/docs/components-dropdown-with-button--default&globals=measureEnabled:false ](url) - the menu that comes as a pop-over and the button which opens the menu - are in the same top div.
<img width="687" alt="image" src="https://github.com/razorpay/blade/assets/54536909/76ac7276-7381-48f2-a7ca-796d2870002b">

<img width="231" alt="image" src="https://github.com/razorpay/blade/assets/54536909/637394b2-50cc-4aaf-937e-1a0e00697482">

What this causes is that if there needs to be sibling elements next to the opener-button (which opens the dropdown) - the top level div needs to be spaced according to the menu - which causes un-even spacing between sibling elements 

<img width="217" alt="image" src="https://github.com/razorpay/blade/assets/54536909/0789cf28-da89-44ab-80c8-9d688192aad0">

If there can be an option for the menu to be floating (with position absolute) - then this problem is fixed

**Comment by saurabhdaware** [comment]
aha got it. makes sense. I'll look into it.

**Comment by prabhasjoshi** [comment]
@saurabhdaware do u want any co-contributors from X frontend team ?

**Comment by saurabhdaware** [comment]
Actually one more easier solution might be to just have good enough `minWidth` set on DropdownOverlay. So irrespecitive of outer element, it should take at least the minimum width that it requires 🤔

**Comment by Jaynil1611** [comment]
@saurabhdaware I will take up the fix for this issue. Will raise a PR with the above-mentioned approach.

**Comment by Jaynil1611** [comment]
#1230

**Comment by prabhasjoshi** [comment]
@saurabhdaware please check
