### ISSUE TITLE
Clearing selected input of controlled dropdown

### ISSUE THREAD

**Issue by prabhasjoshi** [razorpay/blade#1211]
Currently in the [controlled dropdown](https://blade.razorpay.com/?path=/story/components-dropdown-with-select--with-controlled-select&globals=measureEnabled:false) - the api allows us to pass the value to SelectInput.

This lets us select a specific value for example "Bangalore"
<img width="1116" alt="image" src="https://github.com/razorpay/blade/assets/54536909/7603d6a2-5552-4bfe-bc53-f15221cf2c5e">
<img width="444" alt="image" src="https://github.com/razorpay/blade/assets/54536909/6524f8ac-e64b-4c44-8119-bd94f210eef7">

The problem is that we want the control to be able to clear away the selected value when the value to SelectInput is a falsey value.
as shown in this codesandbox - https://codesandbox.io/s/blade-controlled-select-forked-kc86ef?file=/App.tsx 
Select Bangalore > Bangalore gets selected.
Select null > Bangalore doesn't get cleared.

Our use case is the clearing of filters from a separate button.
https://drive.google.com/file/d/1xnotbTooBE1l0vD5L9-J-13OHZHEt7RG/view?usp=sharing 

The lack of this - leaves a part which is still uncontrolled. Thoughts ?

**Comment by prabhasjoshi** [comment]
an update - I observed that If i set the value to an array - of either the selected value or an array of empty string - then this behavior is achieved.
but in the original code sandbox example the value expected is a string - https://codesandbox.io/s/blade-controlled-select-vxg30b?file=/App.tsx

Let's discuss this more

**Comment by divyanshu013** [comment]
Looks like a bug for single selection. @saurabhdaware could you please take a look?
