### ISSUE TITLE
Box: Add support for "textAlign"

### ISSUE THREAD

**Issue by cseas** [razorpay/blade#1225]
We're trying to migrate from Chakra to Blade's Box.

Examples:

https://github.com/razorpay/frontend-website/blob/master/src/components/Sections/ProductsSection.tsx#L16

https://github.com/razorpay/frontend-website/blob/master/src/pages/PaymentPages/modules/HeroSection.tsx#L45

**Comment by saurabhdaware** [comment]
Seems valid 

// cc @divyanshu013 let me know if you see any concern

**Comment by chaitanyadeorukhkar** [comment]
Seems valid. Lets add this 👍

**Comment by divyanshu013** [comment]
We can go ahead, one thing to watch out for is where it may break other components (might need `text-align: start` overrides at such components). Eg:

![image](https://github.com/razorpay/blade/assets/6682655/a669cfca-b1a7-400e-aed4-123a85260e06)

**Comment by anuraghazra** [comment]
Fix in progress https://github.com/razorpay/blade/pull/1229

Will be released soon.
