### ISSUE TITLE
Document `useTheme` hook in storybook

### ISSUE THREAD

**Issue by chaitanyadeorukhkar** [razorpay/blade#1233]
Theres no documentation on `useTheme` instead we only show it being used in examples. We should document this

              Does Blade provide `useTheme` or are users expected to write this hook? Shouldn't this be `useBreakpoint` instead?

_Originally posted by @cseas in https://github.com/razorpay/blade/pull/1187#discussion_r1210632852_

**Comment by saurabhdaware** [comment]
We have issue here to track - #1101

**Comment by divyanshu013** [comment]
Closing this as duplicate, let's track on #1101
