### ISSUE TITLE
Remove Individual Icons Tests

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#1243]
It takes 4 minutes to run the entire test suite locally which is a lot. A lot of these tests are snapshot tests on individual icons which might not be needed.

Its unlikely that one icon breaks but others don't. So we can have tests on common components but individual icons snapshot tests feels a bit of an overkill.

We can probably keep tests on 1-2 icons but might not be needed on every icon.

Icons will keep growing and so is the test runtime

**Comment by anuraghazra** [comment]
+1 on removing 260+ snapshot tests to speed up the tests. 

I think chromatic image snapshots makes more sense here, we already have the catalog of all the icons in storybook. 

> Also, it might also be interesting to check where does the bottleneck coming from, will the test significantly perform faster if we only have 1 file say `icons.test.tsx` where we generate and match all the snapshots?

**Comment by divyanshu013** [comment]
Let's restrict it to ~10 icons ([gif](https://tenor.com/view/do-it-gif-26049397))

**Comment by snitin315** [comment]
We have added sharding on CI with #1473, we can close this.

**Comment by saurabhdaware** [comment]
Should we still do this? tests are still taking a lot of time locally and remove Icon tests wouldn't be very high effort task. What do you think @snitin315?

**Comment by snitin315** [comment]
@saurabhdaware Locally we can easily choose to run specific tests `yarn test:react Autocomplete` or `yarn test:react --testPathIgnorePatterns="(icons|native.test)"`

**Comment by saurabhdaware** [comment]
aha yes this is nice `yarn test:react --testPathIgnorePatterns="(icons|native.test)"`
