### ISSUE TITLE
Open Dropdown on Hover

### ISSUE THREAD

**Issue by prabhasjoshi** [razorpay/blade#1252]
Hi,
In reference to the [blade dropdown which opens from a button component](https://blade.razorpay.com/?path=/story/components-dropdown-with-button-and-link--default&globals=measureEnabled:false)

2 Issues:

1. There should be an option for the dropdown list to open from the hover over the button - and not require a click. By default , it can be based on click - but if the consumer wants - they should allow to open from hover - it should allow that. 
The primary reason for this is accessibility and users are sometimes trained for items to open just from hover. a lot of existing code in x uses this interaction (specifically the split button - https://master--61375a03ff04f6003a18618e.chromatic.com/?path=/story/ui-splitbutton--open-on-hover-split-button)

2. Currently the div which holds the title of the ActionListSection - displays the margin - even though there is no title .. which causes some extra space on top. This div does have aria-hidden = true - but it's not hidden (maybe an additional style to hide it is not added probably).

<img width="1287" alt="image" src="https://github.com/razorpay/blade/assets/54536909/2c1440e3-a997-401b-8e1e-bbba19e2269c">

**Comment by saurabhdaware** [comment]
> Currently the div which holds the title of the ActionListSection - displays the margin - even though there is no title .. which causes some extra space on top. This div does have aria-hidden = true - but it's not hidden (maybe an additional style to hide it is not added probably).

ActionListSection is optional. So if you don't have title, you can just skip that component and directly use `ActionListItem`

**Comment by saurabhdaware** [comment]
https://blade.razorpay.com/?path=/docs/components-dropdown-actionlist--page#actionlist you can check the Simple `ActionList` example here

**Comment by prabhasjoshi** [comment]
@saurabhdaware Thanks this works - and solves 2.

Can we get a prop for openOnHover ? for #1

**Comment by saurabhdaware** [comment]
> Can we get a prop for openOnHover ? for # 1

Divyanshu has started discussion with design regarding this. Will update here once we get response.

**Comment by saurabhdaware** [comment]
You can now handle the controlled state of Dropdown to achieve this - https://codesandbox.io/s/funny-monad-tx7zzd?file=/App.tsx

Although do ask your designer to reach out and confirm with our designers once since it can be an unexpected behaviour. The recommended trigger from us will be click only.

Also for accessibility, we do announce the select as combobox so clicks will be expected over hover.
