### ISSUE TITLE
Render images within Link component

### ISSUE THREAD

**Issue by Kushagra-ag** [razorpay/blade#1253]
Sometimes there's a need to render some logos that are wrapped within an anchor tag. Attached examples from website footer in this PR description.

The `Link` component from Blade only supports `StringChildrenType` type. Hence we cannot pass any JSX to it.
The `IconButton` component will only take the already defined icons in blade.

Need a way to wrap custom logo images (not provided by blade) inside `<a>` tag.

All images in screenshots are clickable and redirecting to their respective links.

<img width="279" alt="Screenshot 2023-06-03 at 11 33 18 AM" src="https://github.com/razorpay/blade/assets/31826645/06214ff2-4e94-414c-a1a1-834773c45b09">

<img width="228" alt="Screenshot 2023-06-03 at 11 34 04 AM" src="https://github.com/razorpay/blade/assets/31826645/840a05f5-8204-40ae-b8a4-61b8ad6e8d79">

**Comment by Kushagra-ag** [comment]
```
<Link href={links.fb.link}>
          Hey!
          <CustomImageBlade src={links.fb.logo} alt="Facebook logo" />
 </Link>
```
where `CustomImageBlade` is just a wrapper around native HTML `<img />` tag.

The above code does work but TS gives out this error - `Type 'Element' is not assignable to type 'ReactText'`

Blade version - 8.6.0

**Comment by saurabhdaware** [comment]
We have an open issue here around the same thing - https://github.com/razorpay/blade/issues/811. Can continue discussing there.
