### ISSUE TITLE
docs: Add Blade logo

### ISSUE THREAD

**Issue by cseas** [razorpay/blade#1255]
I was searching for the Blade logo and couldn't find it anywhere in the docs.

Should be there on the Intro page ideally:
https://blade.razorpay.com/?path=/docs/guides-intro--page

**Comment by divyanshu013** [comment]
@saurav12 plus, we should also link the branding guidelines I think

**Comment by saurav12** [comment]
Agree! Apart from this, in Figma we have a [utility](https://www.figma.com/file/jubmQL9Z8V7881ayUD95ps/Blade---Payment-Light?type=design&node-id=13788-180290&t=JJ3l5SNvwBcF3fBS-4) called wordmarks. We should have the same on the dev side as well.
