### ISSUE TITLE
Refactor: BottomSheet & Modal focus management logic

### ISSUE THREAD

**Issue by anuraghazra** [razorpay/blade#1269]
> Reference: https://github.com/razorpay/blade/pull/1228#discussion_r1219150725

For Modal we are using [FloatingFocusManager](https://floating-ui.com/docs/floatingfocusmanager) which comes with focus return, initial focus, focus trapping etc features, but right now we are using custom logic to achieve those behaviours. 

We can refactor them to remove a lot of code in both BottomSheet and Modal. 

Similarly in [BottomSheet web](https://razorpay.slack.com/archives/G01B3LQ9H0W/p1685443630811999) we can utilize [FloatingOverlay](https://floating-ui.com/docs/FloatingOverlay) which handles stacking of zIndexes.

**Comment by chaitanyadeorukhkar** [comment]
We have completed this partially with https://github.com/razorpay/blade/pull/1340 and implemented this for Modal. Need to do the same for BottomSheet
