### ISSUE TITLE
Tests: Move tests for useTrailingRestrictions into BaseHeader. 

### ISSUE THREAD

**Issue by anuraghazra** [razorpay/blade#1270]
We've moved the useBottomSheetTrailingRestrictions to a generic useTrailingRestrictions, need to write/move the tests also. 

https://razorpay.slack.com/archives/G01B3LQ9H0W/p1686118232234139

**Comment by imrishabh18** [comment]
Hey @anuraghazra, would like to take this up

**Comment by snitin315** [comment]
@imrishabh18 Yes, feel free to work on this.

**Comment by anuraghazra** [comment]
Actually, let's keep this as is for now. 

The logic might be very tricky to generalise, we've added a similar hook for Tabs which was vastly different from BottomSheet's restrictions. 

Let's park this until we have more instances otherwise we might end up with wrong abstraction.
