### ISSUE TITLE
Feature/onBlur prop for radio group component

### ISSUE THREAD

**Issue by Kushagra-ag** [razorpay/blade#1281]
Need an `onBlur` handler on RadioGroup component.
Frontend website has a usecase for triggering analytics call whenever the Radio group element looses focus in a form.

**Comment by anuraghazra** [comment]
Can you link to the existing code that you have in website?

**Comment by Kushagra-ag** [comment]
Sure. https://github.com/razorpay/frontend-website/blob/master/src/components/LeadForm/FormElements.tsx#L255

**Comment by kamleshchandnani** [comment]
how important is this? We have realised in the past things like this doesn't add any value but just bloat analytics data. Would you mind confirming with your product managers how important is this to track? Ideally someone checking and then unchecking is a classic case when you capture it but hovering or losing focus what is the use case for tracking it? Given that we also pay cost for the number and volume of every event.

**Comment by Kushagra-ag** [comment]
Will initiate a discussion on this.

**Comment by chaitanyadeorukhkar** [comment]
Any update on this @Kushagra-ag

**Comment by cseas** [comment]
Thread for follow-up: https://razorpay.slack.com/archives/CTM086NSF/p1686551984416129?thread_ts=1686544488.464609&cid=CTM086NSF

**Comment by snitin315** [comment]
Closing as no carification either on Github/Slack. Feel free to open it again once we have more clarity.
