### ISSUE TITLE
Box: data-* attributes

### ISSUE THREAD

**Issue by cseas** [razorpay/blade#1288]
Add support for data attributes on Box component.

Use-case: https://github.com/razorpay/frontend-website/pull/2160/files#diff-fb19c89ba079ff82c34d4c5f1ecbd36a1600069e7935660de7b312179d4a3fcbR55

**Comment by chaitanyadeorukhkar** [comment]
What was the use case here? Why are we adding `data-*` attributes?

**Comment by cseas** [comment]
We needed this for building Carousel. Relevant discussion with details [here][1].

[1]: https://docs.google.com/spreadsheets/d/1RnjvDwNOAMnrLN2-2KIyEBwwX0cAmKK2JTtI3gNK2rA/edit?disco=AAAA0imfNU8

**Comment by kamleshchandnani** [comment]
Went through the discussion and Ashutosh has proposed some better alternative solutions which I agree with. Closing this in favor of that.
