### ISSUE TITLE
[Bug] Box: Avoid forwarding invalid props

### ISSUE THREAD

**Issue by cseas** [razorpay/blade#1289]
While inspecting a Box component, we can see that it forwards all props as it is to the output html:

<img width="804" alt="Screenshot 2023-06-12 at 8 20 38 PM" src="https://github.com/razorpay/blade/assets/29686866/0689e6fd-78ff-4abe-a7c9-90d165d5021c">

**Comment by saurabhdaware** [comment]
Tracking it here #714. Ideally we shouldn't be forwarding any blade-specific props.
