### ISSUE TITLE
Box: gridTemplateColumns

### ISSUE THREAD

**Issue by cseas** [razorpay/blade#1291]
Please add support for `gridTemplateColumns` property to Box component.

Use-case: 

https://github.com/razorpay/frontend-website/blob/master/src/components/FeaturesGrid/FeaturesGrid.tsx#L29

**Comment by saurabhdaware** [comment]
It's supported - https://codesandbox.io/s/s35q4n?file=/App.tsx&utm_medium=sandpack

<img width="1070" alt="image" src="https://github.com/razorpay/blade/assets/30949385/e34f10c8-8eba-45e8-b267-f3513f72ca32">
