### ISSUE TITLE
Amount component doesn't show 0 decimals with isAffixSubtle

### ISSUE THREAD

**Issue by ShivamKSRazorpay** [razorpay/blade#1307]
`<Amount isAffixSubtle={false} value={10000} /> or
<Amount isAffixSubtle={false} value={10000.00} /> `

**isAffixSubtle** hides the decimals.

Actual output: **₹ 10,000**
Expected output: **₹ 10,000.00**

![image](https://github.com/razorpay/blade/assets/103921926/3081f9b7-3884-4fb1-962b-5492058f4356)

**Comment by saurabhdaware** [comment]
Thanks for creating the issue!!

Looks like it is rounding up when decimals are `.00`. When decimals are `.124` it works. Seems like a bug to me.
