### ISSUE TITLE
Box: Support "initial" and "fit-content" for width

### ISSUE THREAD

**Issue by cseas** [razorpay/blade#1314]
## Problem

I'm working on implementing this design:

<img width="650" alt="Screenshot 2023-06-16 at 2 53 14 PM" src="https://github.com/razorpay/blade/assets/29686866/4121db8c-227d-4139-b5d6-ed30a5cc7843">

Which becomes this on mobile:

<img width="300" alt="Screenshot 2023-06-16 at 2 55 01 PM" src="https://github.com/razorpay/blade/assets/29686866/2c13906b-63ac-4e06-9adf-1d3404b8c3c8">

We want the last item to be on a separate line. Putting `display: block` on it messes up the alignment of the icon and text since their container has `display: flex`.

Code with the issue:
https://github.com/razorpay/frontend-website/pull/2194/files#diff-1f2c8c5821f57c8376ada25679cfc0b957d02788758ba99df29d8ca16b1599b5R96

## Suggestion

I could technically put another wrapper around the wrapper containing the icon and text and put a responsive `display: block` on that. But assuming the goal of the Layout primitives was to avoid *wrapocalypse* like this one.

Please support the "initial" and/or "fit-content" values for width on Box component. So we could write this:

```
<Box width={{ base: '100%', l: 'initial' }}>
```

This will render the correct layout:

<img width="300" alt="Screenshot 2023-06-16 at 3 01 41 PM" src="https://github.com/razorpay/blade/assets/29686866/fe221d01-7c7f-492c-a9d3-d674d4bc3f7f">

**Comment by divyanshu013** [comment]
Besides these we should also add other relevant values in TS, eg. min-content, max-content, inherit, unset, etc. as part of this issue
