### ISSUE TITLE
[Feat]: Support negative spacing tokens in Styled Props

### ISSUE THREAD

**Issue by anuraghazra** [razorpay/blade#1326]
Originally raised by @AnshulNautiyal - [Internal Thread](https://razorpay.slack.com/archives/CJY7W3WFM/p1687239763785379?thread_ts=1682600861.191649&cid=CJY7W3WFM) 

Because we don't support `margin="-spacing.5"` he had to do `margin={-${theme.spacing[5]}px}`

Now `-${theme.spacing[5]}px` throws a TS error because by default TS will resolve this type as `string` and not the concrete `-16px` literal type, thus I suggested him to use:

```jsx
margin={`-${theme.spacing[5]}px` as const}
```

or alternatively we can also do 

```jsx
import { makeSpace } from "@razorpay/blade/utils";

margin={makeSpace(theme.spacing[5])}
```

But i think this is a bit verbose and an inconvenience to opt into interpolation to do negative margins, we should support negative variants for these also:

```jsx
margin="-spacing.5"
```

**Comment by archie252000** [comment]
I think introducing negative values within spacing will make more sense.
We can do this:
```
export const spacing: Spacing = {
  0: 0,
  1: 2,
 -1: -2    //Add negative value
  2: 4,
 -2: -4    //Add negative value
  .
  .
  .
};
```
So this syntax becomes valid ```margin="spacing.-5"```

**Comment by saurabhdaware** [comment]
> ```js
> import { makeSpace } from "@razorpay/blade/utils";
>
> margin={makeSpace(-theme.spacing[5])}
> ```

I am actually favouring this more.

Negative spacings are not as common and adding them to autocomplete might overwhelm the autocomplete. Right now I can type "spacing.5" and hit enter and it will always be the correct spacing.5 but with this addition, I will have to choose between negative and positive variant from AutoComplete of editor everytime.

Introducing this in token-level might also introduce more maintenance. We will have to make sure our positive spacings are in sync with negative spacings.

**Comment by saurabhdaware** [comment]
I don't seem to see any typescript error mentioned in original issue description 🤔 

Was it some intermediate error that got fixed now @anuraghazra?

`theme.spacing['1']` has a type of number so it will correctly type it as `-2px` right?

<img width="412" alt="image" src="https://github.com/razorpay/blade/assets/30949385/fcaeccff-a2d7-4426-855e-5357a21cd37a">

**Comment by anuraghazra** [comment]
> I don't seem to see any typescript error mentioned in original issue description 🤔

No the original error was happening because he was using `-spacing.3`.

**Comment by anuraghazra** [comment]
> Negative spacings are not as common

Sure I think that's a fair point, we can close this for now. If any more usecases come in we will look into this.

**Comment by saurabhdaware** [comment]
Cool. Will close this for now. Can reopen if this becomes major DX issue
