### ISSUE TITLE
Feature/Background Image props on Box

### ISSUE THREAD

**Issue by Kushagra-ag** [razorpay/blade#1327]
Request for adding `background-image` prop on the blade `Box` component.

Along with this other props that control the sizing and position of background image will also be needed. Example of some - 
`background-size, background-position, background-origin, background-repeat`

**Comment by cseas** [comment]
Use-case:

https://github.com/razorpay/frontend-website/pull/2214/files#diff-864784c3dc2a876993920d9e235dadbebacde22e9f874722bd517956441688a8R29
