### ISSUE TITLE
Title: support superscript element

### ISSUE THREAD

**Issue by kadarsh11** [razorpay/blade#1333]
We need the superscript support on Title component to add * as shown in image

<img width="110" alt="Screenshot 2023-06-21 at 11 20 30 AM" src="https://github.com/razorpay/blade/assets/31586309/a18aaf9f-964e-4e0b-8274-0ad3b7fef4a0">
<img width="269" alt="Screenshot 2023-06-21 at 11 21 30 AM" src="https://github.com/razorpay/blade/assets/31586309/8dd6b87a-6e71-460e-8f7a-555d7a147f57">

**Comment by anuraghazra** [comment]
Done in #1338
