### ISSUE TITLE
Box: Support for borderRadius

### ISSUE THREAD

**Issue by kadarsh11** [razorpay/blade#1335]
We need the support of borderRadius prop for Box component

**Comment by anuraghazra** [comment]
@kadarsh11 we already support borderRadius on Box. please check the [docs here.](https://blade.razorpay.com/?path=/docs/components-layout-primitives-box-box--default&globals=measureEnabled:false)
<img width="1096" alt="image" src="https://github.com/razorpay/blade/assets/35374649/a543d372-fabc-4206-aa9e-b407dbd60a47">
