### ISSUE TITLE
Modal: Document default props

### ISSUE THREAD

**Issue by cseas** [razorpay/blade#1357]
I'm going through Modal docs trying to figure out what its default size is but it's not mentioned anywhere:
https://blade.razorpay.com/?path=/docs/components-modal-modal--page&globals=measureEnabled:false

**Comment by Nanak360** [comment]
I can take it up and update the documentation if nobody is working on it

**Comment by snitin315** [comment]
@cseas You can find the defaults here - https://blade.razorpay.com/?path=/docs/components-modal-simplemodal--default&globals=measureEnabled:false

**Comment by snitin315** [comment]
Marking this as resolved.
