### ISSUE TITLE
"ResizeObserver is not defined" error when running Jest

### ISSUE THREAD

**Issue by joel-jaimon** [razorpay/blade#1367]
Getting this error when running Jest with v8.11.3.
<img width="1440" alt="Screenshot 2023-06-27 at 1 12 17 PM" src="https://github.com/razorpay/blade/assets/64752455/394647de-7968-4d88-bd8b-92b6ebe60eca">

**Comment by kkyusufk** [comment]
@joel-jaimon can you add more context around the issue? Maybe a steps to reproduce.

**Comment by chaitanyadeorukhkar** [comment]
You can mock it with this:
```
global.ResizeObserver = jest.fn().mockImplementation(() => ({
  observe: jest.fn(),
  unobserve: jest.fn(),
  disconnect: jest.fn(),
}));
```

**Comment by joel-jaimon** [comment]
I had to [mock](https://github.com/razorpay/dashboard/pull/12709/commits/6e11c5482008cdb5591e1bd6ac60d4969b4fb53c) it in the end, but I just wanted to check with you folks if this can be resolved from the lib itself.

**Comment by chaitanyadeorukhkar** [comment]
Not sure if we'll be able to resolve it on lib end since it would always be client's jest that doesn't have any definitions for ResizeObserver. I can add this to the FAQ section though

**Comment by prabhasjoshi** [comment]
I was also facing the same error - so i setup the mocking for it in my projects initJest.js  file

**Comment by chaitanyadeorukhkar** [comment]
Added in FAQ #1412. Closing this
