### ISSUE TITLE
Tooltip is rendered outside the visible viewport

### ISSUE THREAD

**Issue by Jaynil1611** [razorpay/blade#1372]
While using the tooltip component in the X dashboard, I encountered this issue where the component is rendered outside the viewport. I am trying to render a tooltip on Blade's Text component. I've attached the below video to help you understand this issue better.

[Figma Link](https://www.figma.com/file/kxLqOeCiJc0Qzh6RmoJnX6/Vendor-Advances-(without-PO)?type=design&node-id=801-297390&mode=design&t=MUuu9VQToc8rDkpV-4)

Here is the code snippet I am trying to run:
```js
      <Tooltip content="Total advance selected should be ≤ Payable amount" placement="bottom">
        <TooltipInteractiveWrapper>
          <Text type="placeholder" size="small">
            {notes}
          </Text>
        </TooltipInteractiveWrapper>
      </Tooltip>
```

https://github.com/razorpay/blade/assets/48921037/870b7eca-d8cb-4558-93a5-1b3330c32b9f

**Comment by anuraghazra** [comment]
@Jaynil1611 do you have a PR or code that you can refer? That will help us debug this.

**Comment by Jaynil1611** [comment]
@anuraghazra 
[PR](https://github.com/razorpay/x/pull/6940/files#diff-04aa85978ff5834685aeda92d75a40bcbcbc6a671b2f0b44a88bd64f67b73639)
[File Link](https://github.com/razorpay/x/blob/b2cf409477fa5708b1e569cf42bd3e12e72ebfa1/src/js/views/VendorPayouts/DetailsViewHelpers/DetailsViewHelpers.tsx#L87)

Attaching another video for this PR change.

https://github.com/razorpay/blade/assets/48921037/3ca65151-caa1-4c3c-b74e-3ea8edd58c68

**Comment by anuraghazra** [comment]
Okay found the bug, just a zIndex issue. It's hidden behind the panel. Will raise a patch. 


Uploading Screen Recording 2023-07-05 at 2.05.41 PM.mov…
