### ISSUE TITLE
Allow non-surface colors in Box Component.

### ISSUE THREAD

**Issue by prabhasjoshi** [razorpay/blade#1377]
Currently the box component only allows surface based colors. If we don't use a surface color, it gives a typescript like this:

```
Type '"feedback.background.info.highContrast"' is not assignable to type '"surface.background.level1.lowContrast" | "surface.background.level1.highContrast" | "surface.background.level2.lowContrast" | "surface.background.level2.highContrast" | "surface.background.level3.lowContrast" | "surface.background.level3.highContrast" | { ...; } | undefined'.
```

If we have to build certain design like these: 
<img width="37" alt="image" src="https://github.com/razorpay/blade/assets/54536909/ffd4ed91-8f53-4af6-9c84-a09f169dde14">
 Figma - [link](https://www.figma.com/file/5W5ZUt5umvBXuPvjLqusN3/Generic-Accounting?type=design&node-id=7626%3A264692&mode=dev) 
 
Then we have to enclose a CheckIcon within a box and give it a custom color and border spacing like -> 
 
 ```
 <Box
    backgroundColor="feedback.background.info.highContrast"
    width="spacing.8"
    height="spacing.8"
    display="flex"
    alignItems="center"
    justifyContent="center"
    borderRadius="spacing.8"
  >
    <CheckIcon color="surface.text.normal.lowContrast" size="medium" />
  </Box>
 ```
 
But if we do this, we get a typescript error. 
If for implementing any custom design - I cannot do completely with blade - and I have to restore to using a styled.div - then I am setting myself up to adopt turnarounds where blade coverage will be low - and that should be fixed by allowing all colors for the box component.

Full Slack thread here:
https://razorpay.slack.com/archives/CMQ3RBHEU/p1687934328621829

**Comment by prabhasjoshi** [comment]
@saurabhdaware

**Comment by chaitanyadeorukhkar** [comment]
@prabhasjoshi we want to use Box component only for Layout purposes. For creating a custom component I would recommend using a styled-component directly. Adding support for non-surface colors will go against the philosophy of a Layout component.

**Comment by chaitanyadeorukhkar** [comment]
@prabhasjoshi closing this for now with the conclusion that Box will only support surface colors to stay true to its purpose of being a Layout component.
