### ISSUE TITLE
Box: placeItems

### ISSUE THREAD

**Issue by cseas** [razorpay/blade#1381]
The `place-items` grid property is not supported by Box component.

```tsx
      <Box display="grid" placeItems="center">
        {children}
      </Box>
```

## Workaround

We can specify both alignItems and justifyItems separately to have the same effect.

```tsx
      <Box display="grid" alignItems="center" justifyItems="center">
        {children}
      </Box>
```

**Comment by chaitanyadeorukhkar** [comment]
This shorthand support does not exist on react-native and we want to maintain API consistency across platforms. You can continue using `justifyContent` and `alignItems` to achieve this. Closing this since we won't be adding this and there is a proper solution already.

**Comment by cseas** [comment]
> You can continue using justifyContent and alignItems

justifyContent is different, we need to use `justifyItems`. Even I had to look it up. 🙈 

Do you think there could be a way to add this warning/workaround to show up in the IDE itself? 🤔 
How do other similar libs handle this?

**Comment by saurabhdaware** [comment]
Discussed it internally. Can look into adding this since we have `placeSelf` on styled-props already.
