### ISSUE TITLE
Tooltip component is overriding the aria-label of trigger element

### ISSUE THREAD

**Issue by anuraghazra** [razorpay/blade#1386]
> Reference: https://razorpay.slack.com/archives/CMQ3RBHEU/p1688128540647929
> Demo: https://codesandbox.io/s/infallible-matan-yc7stq?file=/App.tsx

We are redundantly passing aria-label to the trigger element which is overriding the computed aria-label of the Input, it should work as is with aria-describedby only. 

(Need to also see how it will work with RN)

**Comment by archie252000** [comment]
@anuraghazra Can you please explain the desired behaviour? Should ```...makeAccessible({ label: content })``` not override the ```aira-label``` if the trigger element has it already?
