### ISSUE TITLE
Provide Ref based method to open the dropdown

### ISSUE THREAD

**Issue by prabhasjoshi** [razorpay/blade#1389]
Reference thread - https://razorpay.slack.com/archives/CMQ3RBHEU/p1688376773554879 

Currently blade dropdowns provide a way to focus or scrollintoview via ref based methods as mentioned [here](https://blade.razorpay.com/?path=/story/components-dropdown-with-select--with-ref-usage&globals=measureEnabled:false)

We will also need a way to open the dropdown - since a common use-case could be to open the dropdown without a human trigger - let's say to show user a tour of the options available inside it.

Could we please provide this option as this functionality is currently blocking a release.

@saurabhdaware @Jaynil1611

**Comment by chaitanyadeorukhkar** [comment]
There is an ongoing discussion on Slack regarding whether or not this is a valid UX. We can take the decision on what needs to be picked up on tech once we make a decision on design.

**Comment by saurabhdaware** [comment]
Closing this as Opening and Closing Dropdown can be controlled using `isOpen` and `onOpenChange` prop on Dropdown now.

```jsx
<Dropdown isOpen={isOpen} onOpenChange={(isOpen) => setIsOpen(isOpen)}>
</Dropdown>
```

Although do verify the UX once
