### ISSUE TITLE
Some of the Dropdown components not working in Storybook

### ISSUE THREAD

**Issue by ShivamKSRazorpay** [razorpay/blade#1395]
Some of the Dropdown components examples are not working in Storybook.

- https://blade.razorpay.com/?path=/docs/components-dropdown-dropdown--page

![image](https://github.com/razorpay/blade/assets/103921926/2992db5d-cb20-4bed-bdf3-4928e60e7785)

- https://blade.razorpay.com/?path=/story/components-dropdown-with-select--with-header-footer-scrollbar&globals=measureEnabled:false
<img width="1504" alt="image" src="https://github.com/razorpay/blade/assets/103921926/90b4f79f-e40d-4079-a104-2f4d14ecbf66">

**Comment by ShivamKSRazorpay** [comment]
Debugged a little bit, the issue is with rendering of both DropdownHeader & DropdownFooter

**Comment by saurabhdaware** [comment]
so the storybook is published on PR merge and version is published after changeset version bump merge so there is gap in which storybook has latest code but that code isn't released as version yet. It will be fixed after the release happens
