### ISSUE TITLE
Add support for 2xl (1600px) breakpoint

### ISSUE THREAD

**Issue by cseas** [razorpay/blade#1396]
This might be a one off use-case so feel free to close if the request doesn't make sense.

The top polygon component in frontend-website is a tricky one to align correctly with the image and navbar.

<img width="759" alt="Screenshot 2023-07-04 at 10 47 22 PM" src="https://github.com/razorpay/blade/assets/29686866/45a4a176-43f6-4dac-9abc-9a6540c53486">

Refer this comment:
https://github.com/razorpay/frontend-website/pull/2264#discussion_r1252234302

We need to specify a media query that triggers close to 1600px min-width to get its positioning correct on large monitors. We were earlier doing it using the `3xl` breakpoint of Chakra UI. Although the usage is one off, this component will be used on many pages so it's a prominent component for frontend-website.

**Comment by chaitanyadeorukhkar** [comment]
Can you try overriding the theme and adding your own breakpoints? That might work but need to figure out if its worth adding it if its a one-off use-case. What do you think?

**Comment by cseas** [comment]
Only encountered one case for this so far. We can close the issue if no other products have needed styles that only trigger for large monitors.

**Comment by chaitanyadeorukhkar** [comment]
Cool then. Closing it for now. For any future use-cases we can re-open this and have a discussion 👍
