### ISSUE TITLE
Unable to close Multi-select dropdown with footer button

### ISSUE THREAD

**Issue by ShivamKSRazorpay** [razorpay/blade#1416]
I am unable to close the Multi-select dropdown with footer button. I have used the “hidden button focus” hack with DropdownOverlay and DropdownFooter button as shown [HERE](https://codesandbox.io/s/confident-christian-jj5dsn?file=/App.tsx). But this hack doesn’t work with Dropdown BottomSheet and BottomSheetFooter button as shown [HERE](https://codesandbox.io/s/misty-pine-vmn89g?file=/App.tsx:1447-1464).

What is an ideal way to close the DropdownOverlay or BottomSheet with a Dropdown action button click?

**Comment by chaitanyadeorukhkar** [comment]
@saurabhdaware can you check this?

**Comment by ShivamKSRazorpay** [comment]
@saurabhdaware  Thanks for picking it up! Any ETA on the fix? Need it for the Transactions Revamp project delivery.

**Comment by ShivamKSRazorpay** [comment]
@saurabhdaware  this is not completely done, right?
I see this still needs to be done https://github.com/razorpay/blade/issues/1436

**Comment by saurabhdaware** [comment]
@ShivamKSRazorpay Yup ideally we would need something like `isOpen` on Dropdown component itself to do something like this. Have created #1436 for that.

To get you unblocked, we are allowing `isOpen` to BottomSheet to take priority over Dropdown's internal state so you can use that for BottomSheet - https://codesandbox.io/s/modest-matan-4d29f7?file=/App.tsx

But yes for Dropdown on desktop, the current solution is hacky. We'll solve that with something like `isOpen`
