### ISSUE TITLE
Arrow direction is opposite for collapsible link with direction top

### ISSUE THREAD

**Issue by sujoys12** [razorpay/blade#1424]
<img width="242" alt="Screenshot 2023-07-11 at 3 44 36 PM" src="https://github.com/razorpay/blade/assets/78787105/76d3025a-e193-4e10-abcd-9e113cfcb304">

Arrow direction should be up when body is expanded
https://codesandbox.io/s/funny-albattani-shpjtm

**Comment by chaitanyadeorukhkar** [comment]
This is the intended behaviour. The arrow indicates where the body is going to open. Once opened, it flips to the opposite direction. Attaching screenshots of both top & bottom cases

![image](https://github.com/razorpay/blade/assets/24487274/47642503-acff-4746-bebf-c2d128ecfbfb)

![image](https://github.com/razorpay/blade/assets/24487274/8ee4f33a-09d6-4576-941d-5d542570d3b0)

**Comment by chaitanyadeorukhkar** [comment]
Seems to be a bit confusing with conflicting opinions. Discussing with the design team, will get this to closure.
