### ISSUE TITLE
Add `onDrag*`, `onDrop` handlers, and pointerEvents on Box

### ISSUE THREAD

**Issue by inaseem** [razorpay/blade#1449]
Please add the following props to blade components. These props should be supported(atleast on Box) but aren't.

`onDragEnter`
`onDragOver`
`onDragLeave`
`onDrop`
`pointerEvents`
`placeItems` https://github.com/razorpay/blade/issues/1381

**Comment by saurabhdaware** [comment]
Can you also add where you're using onDrag and onDrop handlers?

**Comment by inaseem** [comment]
In XPayroll, we are creating a FileUpload component which should support files drag and drop on the component. I was using Box to wrap the component, but since none of the drag and drop events were available, I had to resort to using a styled.div. 

<img width="380" alt="image" src="https://github.com/razorpay/blade/assets/6770106/5d3f87e8-300b-4835-b309-1417f8a7a88d">
