### ISSUE TITLE
Adding color prop to IconButton

### ISSUE THREAD

**Issue by Gurmanjot** [razorpay/blade#1456]
Is it possible to add `color` prop to the `IconButton` component as there is a requirement to make a copy icon in `primary.brand.500` color

**Comment by AdityaSingh-02** [comment]
Hey I would like to work on this, could you please assign me this issue

**Comment by saurabhdaware** [comment]
https://blade.razorpay.com/?path=/story/components-link--icon-only-link-button&args=icon:CopyIcon;variant:button&globals=measureEnabled:false

is this what you're looking for?

You can achieve it with 
```jsx
<Link variant="button" icon={CopyIcon} />
```

**Comment by saurabhdaware** [comment]
Closing this for now. Will reopen if Link doesn't solve the usecase.
