### ISSUE TITLE
App crash while using Button component  

### ISSUE THREAD

**Issue by mohit23x** [razorpay/blade#1457]
When using the new blade’s Button component in React Native the app crashes, with the following error (refer to screenshot). From the error log it seems to be coming from Reanimated. 
I have tried re-starting the metro server by clearing the cache but the issue still persists. 

<img width="538" alt="image" src="https://github.com/razorpay/blade/assets/36567063/e5571eaf-4161-461b-ba5c-8c74a6c602a2">

Steps to Reproduce:
- In the [PG mobile repo](https://github.com/razorpay/frontend-mobile-app) 
- Import the button from the new Blade and render the app
- On Android, it crashes, and on iOS a red error screen comes (as attached in screenshot)

**Comment by kamleshchandnani** [comment]
Have you checked your re-animated, styled-component version?

**Comment by mohit23x** [comment]
Matching the `react-native-reanimated` version present in blade v7.2.2 fixes the issue. Thanks for the quick response.
