### ISSUE TITLE
Page becomes unscrollable after closing BottomSheet

### ISSUE THREAD

**Issue by 1995navinkumar** [razorpay/blade#1458]
Blade Version : **7.2.2**
Component : **BottomSheet**

### Issue : 
After closing the BottomSheet, the page becomes unscrollable. Found out that the component adds `overflow:hidden`  to document body on open but doesn't remove it on close. 

### Recording : 

[bottom_sheet.webm](https://github.com/razorpay/blade/assets/22029111/751d9dfd-0271-44d2-89d0-2212ba5075f2)

**Comment by anuraghazra** [comment]
@1995navinkumar can you provide a sample code or reproduction of the bug? 

We are unable to reproduce this on our end - https://codesandbox.io/s/runtime-tree-jmry8p?file=/App.tsx

**Comment by anuraghazra** [comment]
Hi @1995navinkumar can you provide the code example, PR or reproduction for the bug? 

We are unable to reproduce the bug on our end: https://codesandbox.io/s/runtime-tree-jmry8p?file=/App.tsx

Also would be useful to know your browser vendor, version.

**Comment by 1995navinkumar** [comment]
Hi @anuraghazra , Here is the forked codesandbox where issue can be reproduced - https://codesandbox.io/s/frosty-feather-vpjvd7?resolutionWidth=320&resolutionHeight=675&file=/index.tsx

If the Modal open and close is controlled at the parent component, this is getting reproduced. Ideally, things should be cleaned up or returned back to previous state when the component gets destroyed.

**Comment by anuraghazra** [comment]
@1995navinkumar got the issue. 

So you are using the BottomSheet in a wrong way, you are always passing the `isOpen` prop as `true` in BottomSheet and then conditionally unmounting the whole BottomSheet. 

```
// bottom-sheet.tsx
<BottomSheet
  isOpen={true}
/>

// app.tsx
{isOpen && <BottomSheetExample setIsOpen={setIsOpen} />}
```

Instead do this: 
https://codesandbox.io/s/bottomsheet-scroll-fix-3x3q97?file=/App.tsx

```
<BottomSheet isOpen={isOpen} setIsOpen={setIsOpen} />
```
