### ISSUE TITLE
Add new variant to blade input for supporting larger input sizes with horizontal label alignment

### ISSUE THREAD

**Issue by Jaynil1611** [razorpay/blade#1474]
We use the below-attached input variant in the X dashboard for most flows. Also, newer flows use the same variant to keep the input consistent between existing & new flows. We request you consider adding this variant in the blade input component to support all use cases across X. @saurabhdaware @prabhasjoshi 

<img width="838" alt="Screenshot 2023-07-26 at 6 22 29 PM" src="https://github.com/razorpay/blade/assets/48921037/27145a38-ac7c-4c70-836b-9b367a21824e">   

Here is a sample design of the new flow being created on X. [Figma](https://www.figma.com/file/cdTS7TAdvN4vhGiIH27s25/Purchase-Orders-V1?type=design&node-id=685-272959&mode=dev) 

[Storybook](https://master--61375a03ff04f6003a18618e.chromatic.com/?path=/story/ui-field--field-with-flat-ui-medium-width) of existing input variant used in X.

**Comment by saurabhdaware** [comment]
Thanks for creating issue. I think @saurav12 can take a look at this once he is back from vacation since he also has earlier context on cohesive flows.

You can continue using your existing implementation till then

**Comment by saurav12** [comment]
We will not be taking up any newer design elements until the _brand refresh_ is complete as we've to follow the new guidelines anyway in the future. Let's use the existing component until then.

**Comment by Jaynil1611** [comment]
@snitin315 @saurabhdaware I would suggest to keep this open issue with lower priority so that we don't lose track of this requirement.

**Comment by saurav12** [comment]
Actually, we should change the name of this issue, it is not about supporting X-dashboard variant. It is more about a larger size input that is needed.

Let's change the name to "Need larger inputs" and put the examples in the comments.

**Comment by Jaynil1611** [comment]
Changed the issue name

**Comment by saurabhdaware** [comment]
In Progress. Will be fixed with #1960

**Comment by anuraghazra** [comment]
Done as part of https://github.com/razorpay/blade/pull/1960
