### ISSUE TITLE
Box backgroundColor issue

### ISSUE THREAD

**Issue by Kushagra-ag** [razorpay/blade#1480]
The following code results in error - ```<Box backgroundColor={{ base: 'brand.primary.300', l: undefined }} />```

`undefined` is not recognized as a valid prop.

More details in this slack thread - https://razorpay.slack.com/archives/C01H13RTF8V/p1690521750962719

**Comment by k-rajat19** [comment]
@saurabhdaware I want to work on this issue, can you please guide me
also I don't have access to Slack, can you  share details that are in the thread as this makes it easier for me to work on this
