### ISSUE TITLE
useTheme hook not working if imported from blade/utils

### ISSUE THREAD

**Issue by lakshay-dutt** [razorpay/blade#1497]
In this [doc](https://master--61c19ee8d3d282003ac1d81c.chromatic.com/?path=/docs/utils-usetheme--page) the import statement mentioned uses the hook from utils, which is not working
`import { useTheme } from '@razorpay/blade/utils';`

Slack Thread - [ref](https://razorpay.slack.com/archives/CMQ3RBHEU/p1690963963557939)

**Comment by saurabhdaware** [comment]
Fixed with #1839
