### ISSUE TITLE
[Enhancement] Support All currencies with Amount component

### ISSUE THREAD

**Issue by ShivamKSRazorpay** [razorpay/blade#1502]
As of now, the Amount component supports only INR & MYR, but it breaks for other currencies. Could you please add support for other currencies as well on priority?

![image](https://github.com/razorpay/blade/assets/103921926/4585a341-1d6f-4968-8d27-36e34d05a364)
![image](https://github.com/razorpay/blade/assets/103921926/7e19b2e2-bd3d-427b-bfc0-28e71607bca8)

**Use-case:**
when a merchant creates a Payment Link with a custom currency and transacts through it.
![image](https://github.com/razorpay/blade/assets/103921926/21f93edb-45f4-4829-8c64-5fdb421a7dd8)

Payments Table in Transactions:
![image](https://github.com/razorpay/blade/assets/103921926/4c31a2c2-2cdf-432c-929e-e8e25ba9970f)
Design link: https://www.figma.com/file/wIuZPvEPsVcFsIdZU6MwtZ/Transactions?node-id=2843%3A646207&mode=dev

**Comment by abhieshekumar** [comment]
+1 to the enhancement request. Will face the issue in SAV screens as well
