### ISSUE TITLE
Missing NodeJS payment docs 

### ISSUE THREAD

**Issue by RajGM** [razorpay/blade#1509]
Docs for NodeJS are missing for POST /payments/:id/capture

![razorPay](https://github.com/razorpay/blade/assets/16620150/74ad2e48-8ac8-43c6-914b-e3bf632993e0)

**Comment by chaitanyadeorukhkar** [comment]
This is unrelated to Razorpay's Design System but thanks for highlighting this. We will pass the feedback on to the related team. It would be awesome if you could raise a ticket to customer support next time, it would be much faster to get it resolved that way 🚀
