### ISSUE TITLE
Dropdown breaks when selecting option with large length

### ISSUE THREAD

**Issue by Anmay5525** [razorpay/blade#1510]
When selecting an option that has big length, dropdown text overflow. It should get truncated ideally.
https://github.com/razorpay/blade/assets/39096639/f6d690a5-6c4c-4be8-b6b1-fd08503e0cd8

<img width="1236" alt="image" src="https://github.com/razorpay/blade/assets/39096639/7ad69086-1f4f-4e23-b42a-011072e2347b">

**Comment by anuraghazra** [comment]
@Anmay5525 thanks for reporting, can you provide a minimal reproduction or link to the PR where you are implementing this?

**Comment by Anmay5525** [comment]
@anuraghazra It is reproducible on story book of blade, just wrap the component in Box and set a small width.

**Comment by saurabhdaware** [comment]
I have merged the PR to fix. It will be fixed in new version that gets released. Thanks for reporting.
