### ISSUE TITLE
Accordion occupies the full width when screen size > 1024px

### ISSUE THREAD

**Issue by sumitd94** [razorpay/blade#1539]
When we have the screen size greater than 1024px, we have the min-width set to 400px in the accordion & it occupies the full width in the modal

<img width="450" alt="Screenshot 2023-08-16 at 3 24 00 PM" src="https://github.com/razorpay/blade/assets/29303618/a048e76b-32e7-4946-ba0b-750a1377d264">

Looks like we will also have to increase the max-width of the entire modal so that the left and right margin get's aligned correctly (of the accordion).

**Comment by iamabhay17** [comment]
hey, I would like to work on in this issue

**Comment by chaitanyadeorukhkar** [comment]
Seems okay to me? Can you help me with a reproducable example?
<img width="1509" alt="Screenshot 2023-08-22 at 12 07 26 PM" src="https://github.com/razorpay/blade/assets/24487274/5e761799-6190-4d38-a55f-2c49b47cecf3">
