### ISSUE TITLE
Not able to control height of the dropdown overlay

### ISSUE THREAD

**Issue by smit95tpatel** [razorpay/blade#1546]
- Currently there is no way to control the height of the dropdown overlay.
- This problem exist when we have a dropdown inside a modal, and the modal height is too small to occupy the dropdown options within it

Sample screen shot

![Screenshot 2023-08-18 at 6 59 07 PM](https://github.com/razorpay/blade/assets/93181930/7c64133e-46be-471b-a7b1-f3c8813e21cd)

**Comment by saurabhdaware** [comment]
Reproduction: https://codesandbox.io/s/floral-browser-hhrs68?file=/App.tsx

Looks like overlay position works when screen end is there but not when parent element strips the dropdown. Will check it out. 

Also in your case, its possible that there might not be enough space on top also so maybe we'll have to see if we can auto-set height of DropdownOverlay based on space that exists.

Thanks for creating the issue!
