### ISSUE TITLE
onClick for the TextInput component

### ISSUE THREAD

**Issue by nickisaacs** [razorpay/blade#1560]
We are adding a datepicker component. For this we are using the TextInput component to be the trigger to open the datepicker. Unfortunately, there is no onClick handler right now to open the datepicker.

The onFocus prop is not sufficient, as we don't want to trigger the datepicker when the user lands on the input component via keyboard navigation. It should trigger either for `onClick` or `onFocus + enter key`.

The 2nd trigger can be achieved by us by using onFocus to add an keyboard event listener for an enter key before showing the datepicker, but we need the onClick for mouse users too.

**Comment by rk9595** [comment]
Can I start working on this issue?
