### ISSUE TITLE
Can we support for a size prop in AccordianItem to adjust the title size?

### ISSUE THREAD

**Issue by udayraj-rzp** [razorpay/blade#1561]
Currently there’s no support to pass text size to its title. 
| Default AccordianItem | A Workaround |
| ---- | ---- |
| <img width="291" alt="image" src="https://github.com/razorpay/blade/assets/103119590/d559e642-7397-46eb-a3b9-144aa5734caf"> | <img width="253" alt="image" src="https://github.com/razorpay/blade/assets/103119590/788f35ac-e179-478f-8c88-92172d052002"> |

For now, using this workaround is solving it -
```
<AccordionItem
  // eslint-disable-next-line
  // @ts-ignore
  title={
    <Text weight="bold" size="medium">
      Why should I assist my client with their KYC?
    </Text>
  }
>
```

Related issue: https://github.com/razorpay/blade/issues/1539

**Comment by udayraj-rzp** [comment]
Yes @anuraghazra, sharing with you over slack.

**Comment by imrishabh18** [comment]
Hey @udayraj-rzp, Can you share the design for this so I can take up this please?

**Comment by saurabhdaware** [comment]
This was fixed with our new Accordion Enhancements. You can use slot in AccordionItemHeader now https://blade.razorpay.com/?path=/story/components-accordion--individual-accordion-item
