### ISSUE TITLE
Broken figma url

### ISSUE THREAD

**Issue by amanzrx4** [razorpay/blade#1565]
- Was just exploring and saw this shorturl is, i think, broken [here](https://github.com/razorpay/blade/blob/b37ab68f181cca9d6505b612bcef65cf85dc7d66/packages/blade/src/components/Card/Card.tsx#L50C15-L50C40)

**Comment by snitin315** [comment]
@anuraghazra Can you fix the URL?

**Comment by anuraghazra** [comment]
Thats a weird redirect.
