### ISSUE TITLE
Allow tooltip to be shown when button is disabled

### ISSUE THREAD

**Issue by parichay28** [razorpay/blade#1574]
Current implementation doesn't show tooltip on hover in case button is in disabled state.

Usecase: Use tooltip to let users know why certain CTAs are in disabled state

Issue Repro: https://codesandbox.io/s/p84w4g?file=/App.tsx&utm_medium=sandpack

**Comment by anuraghazra** [comment]
@parichay28 to make non-interactive components like disabled button interactive you need to wrap the button in TooltipInteractiveWrapper. 

Demo: https://codesandbox.io/s/distracted-smoke-c5hxk2?file=/App.tsx

**Comment by parichay28** [comment]
Ahh missed this 🙈, thanks for sharing. Closing this issue
