### ISSUE TITLE
Add chromatic snapshot tests for ActionList

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#1611]
Current Dropdown snapshots don't take it's ActionList into consideration because its hidden in the initial snapshots. We should have tests of ActionList itself to avoid issues like #1610

**Comment by harshalkaigaonkar** [comment]
Hey @saurabhdaware , i can take this up, if it's still open..

**Comment by ashutosh887** [comment]
@saurabhdaware I think this is merged already

**Comment by saurabhdaware** [comment]
@ashutosh887 no we just have ActionList documentation. We have snapshots on Dropdown component but they are taken with Dropdown closed so don't cover ActionList as part of it.

We have to create a ActionList.stories.tsx and render multiple ActionList combinations there and then create a Kitchen Sink story where we read those stories and render them on one page for snapshots

KitchenSink stories are here - https://blade.razorpay.com/?path=/docs/components-kitchensink-accordion--accordion

**Comment by saurabhdaware** [comment]
Yup you can take this @harshalkaigaonkar. Thanks 🥳

**Comment by harshalkaigaonkar** [comment]
@saurabhdaware , anything specific needed here for combinations, some kind of list?
