### ISSUE TITLE
Box component to support "id" attribute

### ISSUE THREAD

**Issue by lakshay-dutt** [razorpay/blade#1614]
We have a requirement where a cta click will navigate to a section in the page
Earlier we were using the id attribute of `div/section` to achieve this
```
<a href="#blogs">Click here to visit blogs section</a>
.....
some other content
.....
<section id="blogs">some content</section>
.....
some other content
```
But with blade `Box` this id attribute is no longer available,

- How to achieve the in-page scroll without the id?
- why have we not included `id` in the `Box` props

**Please note:** Can't use a styled component here as the implementation is required in the most common component of the repository.

Blocked PR: https://github.com/razorpay/frontend-website/pull/2526

**Comment by snitin315** [comment]
Fixed in #1616.
