### ISSUE TITLE
borderBottom adds border on all the sides of the element

### ISSUE THREAD

**Issue by SagarBajpai** [razorpay/blade#1624]
Issue : 
On adding `borderBottom` property in the box :
<img width="616" alt="Screenshot 2023-09-11 at 8 06 39 PM" src="https://github.com/razorpay/blade/assets/22431429/f7d07715-f0ff-4a75-ba63-5f4ac8d686a5">

the property `border-style : solid` gets added which adds border in the all the sides
<img width="1339" alt="Screenshot 2023-09-11 at 8 07 36 PM" src="https://github.com/razorpay/blade/assets/22431429/1ac3f39d-8b0e-42aa-b223-69a224a9cdb2">

Expected : 
Only `border-bottom-style` should be added as `solid`

**Comment by SagarBajpai** [comment]
@saurabhdaware @snitin315 Can we solve this? this issue is there since several months!

**Comment by snitin315** [comment]
@SagarBajpai Yes, picking this up on priority.

**Comment by snitin315** [comment]
@SagarBajpai This has been fixed in [@razorpay/blade@10.12.0](https://github.com/razorpay/blade/releases/tag/%40razorpay%2Fblade%4010.12.0)
