### ISSUE TITLE
Support `width` prop on ActionList / DropdownOverlay

### ISSUE THREAD

**Issue by parichay28** [razorpay/blade#1660]
*Current Behaviour*

<img width="986" alt="image" src="https://github.com/razorpay/blade/assets/43565572/403ea71f-be56-4ee8-9874-94fcaefb6e2b">

*Expected Behaviour* [Figma](https://www.figma.com/file/9BNM8PnQa4mY4JrGyGuOD7/Bulk-Improvements-Phase-2?type=design&node-id=858-452076&mode=dev)
<img width="618" alt="image" src="https://github.com/razorpay/blade/assets/43565572/616c6dc2-61c2-414b-adbd-f1ae24de9ee2">

**Comment by saurabhdaware** [comment]
Thanks for creating issue. Checking this with our designer on what would be the expected usage.

**Comment by saurabhdaware** [comment]
Hi @parichay28, discussed with designer and I think the consumers should get option to set width of the ActionList.

So ideally we should have a width prop on `DropdownOverlay` component. Currently it doesn't exist but to get unblocked, you can have a Box wrapper around ActionList and set width there.

Here'e example - https://codesandbox.io/s/ckrfhs?file=/App.tsx&utm_medium=sandpack

I'll keep this issue open and tag it as P1. We can eventually add a `width` prop in DropdownOverlay or ActionList itself so extra Box won't be necessary.

**Comment by parichay28** [comment]
Wrapping `ActionList` with `Box` won't work since `DropdownOverlay` has it's own width.
<img width="280" alt="image" src="https://github.com/razorpay/blade/assets/43565572/d12d1c11-90aa-4b75-be85-788b9953bdb7">

**Comment by saurabhdaware** [comment]
@parichay28  DropdownOverlay has 240px min-width so it can't go beyond that. There shouldn't be any usecase to go lower than that I believe since design itself has min-width 240px on figma

**Comment by imrishabh18** [comment]
Hey @saurabhdaware, Can I take up this issue?

**Comment by saurabhdaware** [comment]
yeah sure! Thank you 🥳

**Comment by harshalkaigaonkar** [comment]
Hey @saurabhdaware, can i try this too, if @pritipsingh is okay to?

**Comment by pritipsingh** [comment]
hey @harshalkaigaonkar I am actually done with it just in the testing phase :)

**Comment by pritipsingh** [comment]
Hey @saurabhdaware  apologies for a bit of delay, got caught up with other tasks. but currently I have only added it for web, let me know if this is required for native too?
