### ISSUE TITLE
checkbox alignment

### ISSUE THREAD

**Issue by sudhakar-selva** [razorpay/blade#1716]
we are seeing some differences in checkbox alignment compared to figma component
**Figma**
<img width="360" alt="Screenshot 2023-10-17 at 11 28 53 AM" src="https://github.com/razorpay/blade/assets/88188744/7aefb89b-e790-4452-8e6f-b888a17ce8da">
**Blade**
<img width="409" alt="Screenshot 2023-10-17 at 11 30 28 AM" src="https://github.com/razorpay/blade/assets/88188744/4d4c1df3-005e-4056-a0b2-7e5e6cd7cc1e">

Note: currently checkbox doesn't have flex shrink 0 so if label is long, checkbox shrinks and breaks aspect-ratio - happens in above screenshot (currently added temp workaround by setting flex shrink 0 on checkbox)

**Comment by anuraghazra** [comment]
Can you link to the figma design? Even the figma looks misaligned. 

IMO the label is so long that it should be considered if it can be added as helpText. 

// @saurav12

**Comment by sudhakar-selva** [comment]
@anuraghazra https://www.figma.com/file/C2g3vSWcNWJ2jAQl6cngkb/Gromor-migration-to-LL?node-id=14%3A469695&mode=dev

**Comment by sudhakar-selva** [comment]
> IMO the label is so long that it should be considered if it can be added as helpText.
got it, but i would still recommend not allowing checkbox to shrink

**Comment by saurav12** [comment]
The Figma version is the correct version here. The checkbox sticks to the top always @anuraghazra. The issue with the current design is we are starting the sentence with a `lowercase` letter hence it looks odd. I've attached the comparison here with `uppercase`. I've mentioned the same on the Figma file as well and tagged the designer.

![image](https://github.com/razorpay/blade/assets/4298450/76954272-d548-4900-a70f-9a8b6e909abb)
