### ISSUE TITLE
Dropdown: validate functionality of isDisabled in multi select dropdown

### ISSUE THREAD

**Issue by abhieshekumar** [razorpay/blade#1739]
- There is a use case to display the options that were selected by user at some point in time as read-only.
- Have tried using `isDisabled` prop on `<SelectInput/>` and eventually on `<ActionListItem/>`
- However unable to get the desired behaviour.
- Please help get this validated.
- [Codesandbox](https://codesandbox.io/s/dropdown-disabled-queries-kxplvx?file=/App.tsx)

**Comment by saurabhdaware** [comment]
Thanks for opening the issue. On it. Will fix by eod today.

**Comment by saurabhdaware** [comment]
Created a PR. Will get it reviewed and merged on next working day.

Meanwhile you can check if this is the behaviour that you're expecting - https://github.com/razorpay/blade/pull/1742#issuecomment-1774934611
