### ISSUE TITLE
feat: color tokens on typography component

### ISSUE THREAD

**Issue by Kushagra-ag** [razorpay/blade#1745]
This is a feature request to have `brand.secondary.*` colors as option in the Typography components. Currently they only support `brand.primary.*`

figma - https://www.figma.com/file/fWOrU2jVzrZCpmBONJmL98/%F0%9F%8C%BB-Homepage-UI-Refresh?node-id=6061%3A34435&mode=dev

The token used here is `brand.secondary.500`

Slack reference - https://razorpay.slack.com/archives/CMQ3RBHEU/p1698212788636299

**Comment by snitin315** [comment]
Fixed via #1744
