### ISSUE TITLE
[react-native][bug]: unable to open bottomsheet on mount/render/navigation

### ISSUE THREAD

**Issue by gupta-ji6** [razorpay/blade#1775]
## Description

The use case is to open the [bottomsheet blade component](https://blade.razorpay.com/?path=/docs/components-bottomsheet--default) on navigating to a screen or say on a component mount. It **_works fine on the web_** but doesn't seem to work on react-native maybe because we use https://github.com/gorhom/react-native-bottom-sheet internally in RN.

### Approaches

```jsx
<SimSelectionBottomSheet
	isOpen={isSimSelectionBottomSheetOpen}
	isCtaLoading={isSimVerificationLoading}
	onDismiss={handleSimSelectionDismiss}
	onCtaClick={handleSimVerification}
	phoneNumbers={['+91 999 999 9999', '+61 888 888 8888']}
/>
```

1. ❌ Hardcode `isOpen` as true, doesn't work.
2. ❌ Make the `isSimSelectionBottomSheetOpen` state value true by default, it doesn't work.
```jsx
  const [isSimSelectionBottomSheetOpen, setIsSimSelectionBottomSheetOpen] = useState(false);
```
3. ❌ Make it true on first render with `useEffect` - doesn't work.
```jsx
useEffect(() => {
	setIsSimSelectionBottomSheetOpen(true);
}, []);
``` 
4. ✅ Make it true with timeout in `useEffect` - works for some reason.
```jsx
useEffect(() => {
  setTimeout(() => {
    setIsSimSelectionBottomSheetOpen(true);
  }, 1000);
}, []);
```

### Web

https://codesandbox.io/s/blade-rn-bottomsheet-issues-ysh6rx?file=/BottomSheetRadioIssue.tsx

### React Native

1. Clone https://github.com/gupta-ji6/blade-react-native-issues
2. Run locally.
3. On the home page, click on "See BottomSheet Issues"

Refer following file - https://github.com/gupta-ji6/blade-react-native-issues/tree/main/src/screens/BottomSheetIssues

## Environment

```
	"@razorpay/blade": "10.14.7",
    "@react-navigation/native": "6.1.9",
    "@react-navigation/native-stack": "6.9.16",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-gesture-handler": "2.13.4",
    "react-native-reanimated": "3.5.4",
    "react-native-safe-area-context": "4.7.4",
    "react-native-screens": "3.27.0",
    "react-native-svg": "13.14.0",
    "styled-components": "5.3.6"
```

**Comment by anuraghazra** [comment]
Okay, got it. Forgot to set [initial](https://gorhom.github.io/react-native-bottom-sheet/props#index) index when isOpen is true thus it's always rendering in closed state. 

Will raise a patch for this.
