### ISSUE TITLE
[react-native][bug]: unable to dismiss bottomsheet from a button click inside it

### ISSUE THREAD

**Issue by gupta-ji6** [razorpay/blade#1776]
## Description

The use case is to dismiss the [bottomsheet blade component](https://blade.razorpay.com/?path=/docs/components-bottomsheet--default) from a button click inside it. It **_works fine on the web_** but doesn't seem to work on react-native maybe because we use https://github.com/gorhom/react-native-bottom-sheet internally in RN.

```jsx
      <BottomSheet isOpen={isOpen} onDismiss={onDismiss}>
        <BottomSheetHeader title="Select SIM" onBackButtonClick={onDismiss} />
        <BottomSheetFooter>
            {/* FIXME: Clicking on Close button doesn't close bottomsheet, it works on web */}
            <Button onClick={onDismiss} variant="secondary" isFullWidth>
              Close
            </Button>
        </BottomSheetFooter>
      </BottomSheet>
```

### Web

https://codesandbox.io/s/blade-rn-bottomsheet-issues-ysh6rx?file=/BottomSheetRadioIssue.tsx

### React Native

1. Clone https://github.com/gupta-ji6/blade-react-native-issues
2. Run locally.
3. On the home page, click on "See BottomSheet Issues"

Refer following file - https://github.com/gupta-ji6/blade-react-native-issues/tree/main/src/screens/BottomSheetIssues

## Environment

```
	"@razorpay/blade": "10.14.7",
    "@react-navigation/native": "6.1.9",
    "@react-navigation/native-stack": "6.9.16",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-gesture-handler": "2.13.4",
    "react-native-reanimated": "3.5.4",
    "react-native-safe-area-context": "4.7.4",
    "react-native-screens": "3.27.0",
    "react-native-svg": "13.14.0",
    "styled-components": "5.3.6"
```

**Comment by anuraghazra** [comment]
This will be fixed with: https://github.com/razorpay/blade/issues/1777#issuecomment-1786956260
