### ISSUE TITLE
[TextInput/react] Using input type=text instead for type=number and manually blocking invalid input using KeyPress

### ISSUE THREAD

**Issue by haquezameer** [razorpay/blade#178]
### Why use `Keypress` to block invalid number inputs?

Input `type=number` is handled differently in Chrome vs Firefox.

**Chrome**
If input has a type of `number`, in Chrome, any kind of invalid inputs like `abc` etc would be blocked and the same would not be rendered as the value inside the input.

**Firefox**
If input has type of `number`, even if the user input is invalid like `abc`, it still gets rendered on the input value even though the value does not actually change, because firefox does not fire the `change` event even if it is rendering it. After rendering, on blur, firefox will render a red border on the input signifying that the input was invalid.

This is not the behaviour we want, hence we use `keyPress` event for listening for the input and then prevent the default behaviour if it is an invalid value.

Demo: https://codesandbox.io/s/typenumberinconsistencies-mfgq5?file=/src/App.js
Uncomment the onKeypress handlers to check the fix

### Why use type=text internally when consumer is passing type=number?

In both firefox & chrome, number inputs can have `-` sign in the start of the input but not at the end. Some input like `123456-` makes the input invalid and calls `onChange` with an empty string value `""`. This especially is a problem with the `Floating Label Style`, as it marks the value is empty, thus when the user blurs the input, the label comes down to initial position breaking styles.

To fix this, we use `type=text` and keep blocking invalid numbers using the `Keypress` handler as mentioned above. Since we are using `type=text`, we need some way to open up the number keyboard by default on mobile browsers. For this we use the `inputMode` attribute. There is decent support for inputMode and due to lack of other solutions not found during dev, this seemed like the most viable solution.

Demo: https://codesandbox.io/s/invalid-character-minus-pmobk?file=/src/App.js:710-716
Try using a string like `1232424-` and see console output

More on inputMode here: https://css-tricks.com/everything-you-ever-wanted-to-know-about-inputmode/

**Comment by divyanshu013** [comment]
Closing since this was related to https://github.com/razorpay/blade-old
