### ISSUE TITLE
Theme, colorScheme, brandColor change option not working for sandbox playground

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#1800]
Storybook apparently deprecated the `globals` props which we used for setting themes. Couldn't find any documentation on what is alternative. Even jsdoc just says deprecated and its not working as expected anymore.

<img width="553" alt="image" src="https://github.com/razorpay/blade/assets/30949385/16c3e3e1-9859-40eb-9c34-466b78a7d367">

This link is supposed open bankingTheme with colorScheme dark but does not anymore - https://blade.razorpay.com/?path=/story/guides-intro--page&globals=themeTokenName:bankingTheme;colorScheme:dark

**Comment by nolostra** [comment]
https://stackoverflow.com/questions/75955311/warn-define-ts-jest-config-under-globals-is-deprecated

please Check if this working for your project . Seems to works for my project !!

**Comment by saurabhdaware** [comment]
Looks like it got fixed with this PR - https://github.com/razorpay/blade/pull/1889

This fixed our issue - `context.globals` --> `context.store.globals`
