### ISSUE TITLE
Add templates for PR and contributions.

### ISSUE THREAD

**Issue by pritipsingh** [razorpay/blade#1828]
Hey I couldn't find a proper contribution guide for commit message & PR creation. An addition of templates would be nice!

**Comment by saurabhdaware** [comment]
We don't have any guidelines on commits as such since while merging we merge with squash and merge so only PR title matters (for this we have github action that fails and recommends a title)

But yes having PR template is something we discussed and would be helpful. Thanks for suggestion.

**Comment by saurabhdaware** [comment]
We added PR template in this PR https://github.com/razorpay/blade/pull/1937
