### ISSUE TITLE
Tooltip component - Content is not getting wrapped inside tooltip

### ISSUE THREAD

**Issue by AnkitaBagale** [razorpay/blade#1842]
Tooltip component - Content is not getting wrapped inside tooltip if content has no space in the text.

<img width="646" alt="image" src="https://github.com/razorpay/blade/assets/69760792/7d110d18-4dab-4f93-b2c7-6676dcfc75e7">

**Comment by anuraghazra** [comment]
@AnkitaBagale can you provide the Code for this? 

We might need to break the word, and this should be resolved via https://github.com/razorpay/blade/pull/1782

**Comment by AnkitaBagale** [comment]
@anuraghazra Tootip's content prop accepts only string. might need changes in TooltipContent component.

```
          <Tooltip content={item.name} placement="bottom">
            <TooltipInteractiveWrapper width="500px">{trimmedName}</TooltipInteractiveWrapper>
          </Tooltip>
```
