### ISSUE TITLE
Carousel onChange fires on parent component re render

### ISSUE THREAD

**Issue by Akshay090** [razorpay/blade#1863]
Stackblitz [link](https://stackblitz.com/edit/g6p4mp?file=App.tsx)

When the parent component re renders the onChange of Carousel fires, which shouldn't be happening 😿

**Comment by AritraLeo** [comment]
So the problem is from Slide 3/4 it comes back to Slide 1 when next is clicked (onChange is triggered). If I am missing something please let me know and if this is the exact problem then I am on it please provide me the link to the page in your repo

**Comment by anuraghazra** [comment]
Fixed in #1895
