### ISSUE TITLE
Card : requires `minHeight` prop

### ISSUE THREAD

**Issue by iamakshatjain** [razorpay/blade#1934]
Card component so far accepts only a `height` prop, when using height with `100%`, the size of the card changes with or without the data. This might leave some empty real estate around the web page. 
To solve for similar problems, this requires a `minHeight` prop within the Card component to prevent such UX breakage
slack : https://razorpay.slack.com/archives/CMQ3RBHEU/p1704286719871369

**Comment by AritraLeo** [comment]
I'd like to work on this issue but I am so sorry that I can't view your slack page. Please give me a bit more insight about the issue, like the name of the file and so on!

**Comment by iamakshatjain** [comment]
> I'd like to work on this issue but I am so sorry that I can't view your slack page. Please give me a bit more insight about the issue, like the name of the file and so on!

@AritraLeo nothing much on slack, you can checkout this file https://github.com/razorpay/blade/blob/master/packages/blade/src/components/Card/Card.tsx

minHeight and minWidth are not available as props here

**Comment by AritraLeo** [comment]
> > I'd like to work on this issue but I am so sorry that I can't view your slack page. Please give me a bit more insight about the issue, like the name of the file and so on!
> 
> @AritraLeo nothing much on slack, you can checkout this file https://github.com/razorpay/blade/blob/master/packages/blade/src/components/Card/Card.tsx
> 
> minHeight and minWidth are not available as props here

cool thanks for the file path !

**Comment by AritraLeo** [comment]
> > I'd like to work on this issue but I am so sorry that I can't view your slack page. Please give me a bit more insight about the issue, like the name of the file and so on!
> 
> @AritraLeo nothing much on slack, you can checkout this file https://github.com/razorpay/blade/blob/master/packages/blade/src/components/Card/Card.tsx
> 
> minHeight and minWidth are not available as props here

I've gone through the files related to the issue seems like I just have to add minHeight and minWidth props to CardProps 
Like minHeight?: BoxProps['param'] now BoxProps extends LayoutProps that has minHeight and minWidth keys. 

I'll proceed with this after confirmation and please give me the PR message last one was editted because the message was not apt. 

Thanks!

**Comment by iamakshatjain** [comment]
> > > I'd like to work on this issue but I am so sorry that I can't view your slack page. Please give me a bit more insight about the issue, like the name of the file and so on!
> > 
> > 
> > @AritraLeo nothing much on slack, you can checkout this file https://github.com/razorpay/blade/blob/master/packages/blade/src/components/Card/Card.tsx
> > minHeight and minWidth are not available as props here
> 
> I've gone through the files related to the issue seems like I just have to add minHeight and minWidth props to CardProps Like minHeight?: BoxProps['param'] now BoxProps extends LayoutProps that has minHeight and minWidth keys.
> 
> I'll proceed with this after confirmation and please give me the PR message last one was editted because the message was not apt.
> 
> Thanks!

@AritraLeo Yes, add to CardProps and you also would have to pass to CardProps explicitly like other `height`, `width` props

**Comment by AritraLeo** [comment]
> > > > I'd like to work on this issue but I am so sorry that I can't view your slack page. Please give me a bit more insight about the issue, like the name of the file and so on!
> > > 
> > > 
> > > @AritraLeo nothing much on slack, you can checkout this file https://github.com/razorpay/blade/blob/master/packages/blade/src/components/Card/Card.tsx
> > > minHeight and minWidth are not available as props here
> > 
> > 
> > I've gone through the files related to the issue seems like I just have to add minHeight and minWidth props to CardProps Like minHeight?: BoxProps['param'] now BoxProps extends LayoutProps that has minHeight and minWidth keys.
> > I'll proceed with this after confirmation and please give me the PR message last one was editted because the message was not apt.
> > Thanks!
> 
> @AritraLeo Yes, add to CardProps and you also would have to pass to CardProps explicitly like other `height`, `width` props

Thnx I'll request the PR shortly !
