### ISSUE TITLE
Skeleton : `minHeight` and `minWidth` prop not working

### ISSUE THREAD

**Issue by iamakshatjain** [razorpay/blade#1946]
`minHeight` and `minWidth` is not passed to <PulseAnimation /> component here https://github.com/razorpay/blade/blob/master/packages/blade/src/components/Skeleton/Skeleton.tsx#L36-L39

**Comment by AritraLeo** [comment]
Please review my PR - changes to packages/blade/src/components/Skeleton/Skeleton.tsx added minHeight and minWidth prop 
and let me know if any changes are required !
Thank You.
