### ISSUE TITLE
DropdownOverlay within bottomsheet occupies the entire space(React-Native)

### ISSUE THREAD

**Issue by shridhar52war** [razorpay/blade#1956]
- There seems to be an issue with the DropdownOverlay when used within the Bottomsheet.
- When used with SelectInput, looks like the `DropdownOverlay` is getting trimmed because of another `View` may be. 🤔 
- Please find the attached video for the issue faced and also code snippet of how it is used. 
Just FYI, we were implementing the design given in this [figma](https://www.figma.com/file/WIfh4tNkGpA5q7YyybcqF8/Account-and-Settings?type=design&node-id=2824-35540&mode=design&t=S5nN8vRNzIWlJJXq-0)

Listing the dependencies used on mobile app
```
"@razorpay/blade": "10.18.0",
"react-native": "0.72.7",
"@gorhom/bottom-sheet": "4.5.1",
"@gorhom/portal": "1.0.14",
"@floating-ui/react-native": "0.10.1",
```

```
const GstUpdateBottomSheet: React.FC<GstBottomSheetProps> = ({
  isOpen,
  onClose,
  defaultGst = '',
  gstList = ['1selectedGSTIn', '2selectedGSTIn', '3selectedGSTIn', '4selectedGSTIn', '5'],
}) => {
  return (
    <BottomSheet key="gst-update-bottomsheet" isOpen={isOpen} onDismiss={onClose}>
      <BottomSheetHeader title="Edit GST detail" />
      <BottomSheetBody>
        <Dropdown selectionType="single">
          <SelectInput
            label="City"
            placeholder="Select your City"
            defaultValue="mumbai"
            name="action"
            onChange={({ name, values }) => {
              console.log({ name, values });
            }}
            onClick={e => {
              console.log('onClick', e);
            }}
          />

          <DropdownOverlay>
            <ActionList>
              <ActionListItem title="Mumbai" value="mumbai" />
              <ActionListItem title="Pune" value="pune" />
              <ActionListItem title="Hyderabad" value="hyderabad" />
            </ActionList>
          </DropdownOverlay>
        </Dropdown>

        <Box>
          <Text>Want to add another GST number? </Text>
          <Text>
            Only GSTIN linked to your PAN card are shown here. If you want to link a different GST
            number, please create a new Razorpay Account
          </Text>
        </Box>
      </BottomSheetBody>
      <BottomSheetFooter>
        <Button isFullWidth onClick={handleGstSubmit}>
          Submit
        </Button>
      </BottomSheetFooter>
    </BottomSheet>
  );
};
```

https://github.com/razorpay/blade/assets/56016210/ecc6d08a-b6d5-4419-bcbe-51b77e4e8eeb

**Comment by shridhar52war** [comment]
@chaitanyadeorukhkar Please tag/assign the relevant folks if required.

**Comment by saurabhdaware** [comment]
Heya, as per our design guidelines, dropdown is mostly a web component only and in mobile screens, bottomsheet is supposed to be used instead. So in your case, it will open a stacked bottomsheet when second select is clicked. 

We do handle basic working of Dropdown though so let me know if dropdown still has any valid usecases in react-native, we can explore handling these cases of dropdown + bottomsheet.
