### ISSUE TITLE
Allow Table row hover state and click action even when row is not selectable

### ISSUE THREAD

**Issue by sujoys12** [razorpay/blade#1966]
Currently hover state and click action is only possible for selectionType single and multiple, i.e. row needs to be selectable.

There are some cases where we need a hover state on table row with selectionType as none. As there are few tables in X where we render action btns on hover, but row is not selectable.

**Comment by chaitanyadeorukhkar** [comment]
I understand hover state but what do you mean by click action? Would exposing an event on `TableRow` for `onMouseEnter` solve this?
