### ISSUE TITLE
ActionListSection background is weird

### ISSUE THREAD

**Issue by nickisaacs** [razorpay/blade#1969]
Replicated here: https://stackblitz.com/edit/jomiyj?file=index.tsx,App.tsx

(Used the bankingTheme with dark variant)

The section has this dark background which looks like a bug. I don't see a dark theme here to compare it to https://www.figma.com/file/jubmQL9Z8V7881ayUD95ps/Blade-DSL?node-id=30043%3A576428&mode=dev

<img width="736" alt="image" src="https://github.com/razorpay/blade/assets/2580911/64fe7687-8519-4033-b128-65d7f94fc8cf">

**Comment by saurabhdaware** [comment]
Hi, this should be fixed with rebranding - https://stackblitz.com/edit/jomiyj-nkvj7u?file=App.tsx,package.json,index.tsx,Logger.tsx

Let me know if this is a blocker on v10, I can create a backtrack PR.

**Comment by nickisaacs** [comment]
not a blocker, thanks
