### ISSUE TITLE
[FEATURE]: Make Alert component's leading icon configurable

### ISSUE THREAD

**Issue by anuraghazra** [razorpay/blade#2019]
Given that we've made the Toast component to have default icons + the ability to customise the icon, We should do the same for Alert component.

**Comment by AritraLeo** [comment]
> Given that we've made the Toast component to have default icons + the ability to customise the icon, We should do the same for Alert component.

Hi @anuraghazra I see am PR is open but some changes are requested in it. If this issue is still open please let me know I'd love to work on this issue!

**Comment by saurabhdaware** [comment]
Hey @AritraLeo, I think we can wait for @harsh9975 in case he is already working on it.

**Comment by AritraLeo** [comment]
Ya sure I was just curious
