### ISSUE TITLE
React Native is broken after i18n features were added to Amount component

### ISSUE THREAD

**Issue by chaitanyadeorukhkar** [razorpay/blade#2036]
- Cannot get React native (ios or android) working after taking a pull from master
- Error seems to be arising from the i18n library

**Error:**
![image](https://github.com/razorpay/blade/assets/24487274/180ba982-4038-487b-84ac-62ca795f85b9)

**Comment by chaitanyadeorukhkar** [comment]
@anuraghazra @saurabhdaware @snitin315 can you folks try reproducing this and confirm once?

**Comment by snitin315** [comment]
I'm checking this.

**Comment by tarun-khanna** [comment]
Hey @snitin315 , I've already shared the findings [here](https://razorpay.slack.com/archives/CMQ3RBHEU/p1708587851376169?thread_ts=1708585859.885849&cid=CMQ3RBHEU). 

> The issue is with the submodule imports @razorpay/i18nify-js/currency .
> It works if we import i18nify SDK in this format @razorpay/i18nify-js but somehow breaks in sub-module imports for android and IOS.
> Not really sure why is this breaking for android/ios but works for web (working example), so I'll need some time to investigate this.
