### ISSUE TITLE
Dropdown[SelectInput] label alignment issue

### ISSUE THREAD

**Issue by amandal97** [razorpay/blade#2038]
For a SelectInput with `lablePosition=left`, the UI is rendered as shown below:
<img width="502" alt="Screenshot 2024-02-22 at 2 18 58 PM" src="https://github.com/razorpay/blade/assets/45780866/fdc2b243-3ee4-474a-992e-f7c31593103c">

The UI looks weird as there is a lot of space between the label and the SelectInput.

We can see a `margin-right: 16px` between the label and the SelectInput. Would it be possible make the lable right aligned?

<img width="574" alt="Screenshot 2024-02-22 at 2 21 37 PM" src="https://github.com/razorpay/blade/assets/45780866/bd9d4892-a331-4397-b2d3-3ecf1d852515">

**Comment by saurabhdaware** [comment]
This is resolved I believe - https://razorpay.slack.com/archives/CMQ3RBHEU/p1708594719003259?thread_ts=1708592216.367619&cid=CMQ3RBHEU
