### ISSUE TITLE
[FEATURE]: Input Component for Adding Email IDs

### ISSUE THREAD

**Issue by amandal97** [razorpay/blade#2075]
**We have a feature where:**
- User can enter the email address of the recipients
- Send relevant data to the mentioned emails addresses

**The component ideally should:**
1. Allow the user to enter the email address
2. On pressing `Enter` the email address should be loaded as a `Tag` . (Just like Multi-select Dropdown)
3. If invalid email is entered, `negative` colour to be displayed for the respective Tag.

**_Notes:_**
- A sample of the component behaviour is shared below
- We achieved similar behaviour using the `Creatable Items` concept provided in the `Multiselect Autocomplete` . Example shared below.

https://github.com/razorpay/blade/assets/45780866/36798747-d030-467f-9366-573a15c9cc4b

https://github.com/razorpay/blade/assets/45780866/c141ba78-de81-473e-a3aa-22ffa1b4753d

**Comment by AritraLeo** [comment]
Hi, I think I'd like to work on this issue where you need a component (custom) to tag every email id on **Enter** .
Can you please share the folder path that I should look into to incorporate the changes?

**Comment by saurabhdaware** [comment]
Hey @AritraLeo, We need to discuss API of this before we take it up. 

Will keep you posted on any updates but we might pick this up internally in the team since it requires several discussions.

**Comment by anuraghazra** [comment]
Done as part of #1459
