### ISSUE TITLE
noreferrer in rel attribute of button rendered as link

### ISSUE THREAD

**Issue by 1995navinkumar** [razorpay/blade#2125]
## Issue description 

When a blade button is rendered as link using `href` attribute, by default it sets `rel` attribute values as `noreferrer noopener`. Because of this, `document.referrer` is empty in the linked page and in analytics, we miss out the source of the traffic that landed on the linked page, leading to funnel breakage. 

Refer : https://razorpay.com   --> Login/Signup CTAs

## Expected behaviour

When button is rendered as link, do not set any `rel` attribute by default. Users can explicitly pass `rel` prop if needed.

**Comment by anuraghazra** [comment]
@1995navinkumar Will look into this and get back to you.

**Comment by 1995navinkumar** [comment]
@anuraghazra  Any update on this?

**Comment by anuraghazra** [comment]
@1995navinkumar do you want to pick it up? and raise a PR?

**Comment by naveen8801** [comment]
Hey @anuraghazra, I want to contribute to this amazing design system. 
Can I raise a PR for this issue, I think I already know what needs to be done 😃

**Comment by saurabhdaware** [comment]
Sorry for the late response but yes @naveen8801 you can take it up

**Comment by anuraghazra** [comment]
Fixed in #2308
