### ISSUE TITLE
helpText in Radio component has red color

### ISSUE THREAD

**Issue by AnkitaBagale** [razorpay/blade#2132]
helpText in Radio component has red color, it should be muted or subtle.
<img width="577" alt="image" src="https://github.com/razorpay/blade/assets/69760792/2b1845b5-fa71-48c5-a564-09507b0834c3">

```
<RadioGroup
                label=""
                name="beneficiaryInfo"
                size="medium"
                onChange={handleBeneficiaryInfoChange}
                value={formState.beneficiaryInfo}
              >
                <Radio value={beneficiaryInfoMap.details} helpText="Bank details/UPI ID/Wallet no.">
                  Beneficiary details
                </Radio>
                <Radio value={beneficiaryInfoMap.id} helpText="Works for existing contacts only">
                  RazorpayX Fund account ID
                </Radio>
</RadioGroup>
```

**Comment by anuraghazra** [comment]
🤔 Weird this should not happen. 

Can you link to the PR/Code for this?

**Comment by AnkitaBagale** [comment]
@anuraghazra code PR. this is happening in v11 dark mode, working fine in v10
https://github.com/razorpay/x/pull/7658

**Comment by anuraghazra** [comment]
@AnkitaBagale I've raised a fix for this https://github.com/razorpay/blade/pull/2175

Seems like while rebranding we accidentally added isNegative prop to helpText
