### ISSUE TITLE
Not able to add modal components conditionally

### ISSUE THREAD

**Issue by AnkitaBagale** [razorpay/blade#2170]
Getting error for adding conditional ModalHeader and ModalFooter.
[Blade: Modal]: Modal only accepts ModalHeader, ModalBody and ModalFooter as children

https://github.com/razorpay/x/pull/7659/files#diff-01f4c87d8c2e05ab88e07dfce93a8adad4664943fe057e44b39ab75cf978f243R181

**Comment by anuraghazra** [comment]
@AnkitaBagale nice find, seems like it was an issue with the children verification function, I've raised a fix.

**Comment by anuraghazra** [comment]
@AnkitaBagale this is released in https://github.com/razorpay/blade/releases/tag/%40razorpay%2Fblade%4011.17.1
