### ISSUE TITLE
Input field gets zoomed in on iOS devices for default size

### ISSUE THREAD

**Issue by 1995navinkumar** [razorpay/blade#2210]
Steps to reproduce : 
- Visit https://accounts.razorpay.com in iOS mobile
- Click on the input field
- Input Field gets zoomed in and doesn't reset after.

Impact : 
- UX is affected. 

Cause : 
- While checking the behaviour, it seems like ios zooms in the input field when font-size is less than 16px. Default font-size for blade TextInput component is 14px. 

Suggestion : 
- Can we make default size to be 16px? 
- We can add support for smaller size and consumers can set it explicitly if needed.

```js
   size : {
      small : "14px",
      medium : "16px" // default
      large : "18px"
   }
```

**Comment by saurabhdaware** [comment]
I think a solution for this is discussed in this issue - https://github.com/razorpay/blade/issues/1476#issuecomment-1659579139

Let me know if it doesn't work, we can reopen and find other solution
