### ISSUE TITLE
For sticky first column, cells with a relative position are overlapping with the first column

### ISSUE THREAD

**Issue by sujoys12** [razorpay/blade#2215]
reproducible link - https://stackblitz.com/edit/mtfjrx-pdr37z?file=App.tsx
slack - https://razorpay.slack.com/archives/C044FVB7UQL/p1716890676392609?thread_ts=1714650255.488099&cid=C044FVB7UQL

**Comment by Sumitmaithani** [comment]
Hi, can I take this issue up?

**Comment by saurabhdaware** [comment]
Hey @Sumitmaithani, Thanks for requesting but this is picked up internally since we were making some changes to the component itself.
