### ISSUE TITLE
Broken links in readme.md

### ISSUE THREAD

**Issue by ShashankaNataraj** [razorpay/blade#2216]
The “white labelling” link redirects to a broken storybook page

<img width="1024" alt="image" src="https://github.com/razorpay/blade/assets/650317/26a0f832-388c-40a8-bea3-8bf2b59d2a7c">

Edit: this one is broken as well:
[CSS Variables for non-React Projects](https://blade.razorpay.com/?path=/docs/tokens-css-variables--page)

Same with [RFCs](https://github.com/razorpay/blade/tree/docs/make-docs-pretty/rfcs)as well. This one points to a file in a deleted branch.

**Comment by saurabhdaware** [comment]
Thanks for pointing out. We'll keep it open for anyone who wants to take it

**Comment by dsundarpaul** [comment]
Hi @saurabhdaware, I want to contribute to this issue. Please provide me with the working link that needs to be replaced.

**Comment by shraddha761** [comment]
Is this  open. Would like to work on

**Comment by snitin315** [comment]
@shraddha761 yes, feel free to send a PR

**Comment by Anshgrover23** [comment]
@ShashankaNataraj @snitin315 plss review my pr. ihave solved this issue
