### ISSUE TITLE
ProgressBar: not showing percentage with decimals

### ISSUE THREAD

**Issue by AnkitaBagale** [razorpay/blade#2227]
```
           <ProgressBar
              type="meter"
              showPercentage
              size="large"
              variant="circular"
              color={getProgressBarColor()}
              value={0.1}
            />
```
<img width="382" alt="image" src="https://github.com/razorpay/blade/assets/69760792/1076f165-9e5f-4ffe-89e0-9cf4b41d5159">

**Comment by saurabhdaware** [comment]
We'll check with design and get back. Thanks

**Comment by chaitanyadeorukhkar** [comment]
When type is `meter` we should show decimals, when type is `progress`, we should round it off
