### ISSUE TITLE
[Input/react]: width=auto props not working

### ISSUE THREAD

**Issue by avinashdvv** [razorpay/blade#224]
```
<Size width="100px">
  <View>
    <TextInput
      type="number"
      width="auto"
      name="card_number"
      label="Card number"
      variant="filled"
      labelPosition="top"
      placeholder="Enter 16 digit card number"
      errorText={formikProps.touched.card_number && formikProps.errors.card_number}
    />
  </View>
</Size>
```

TextInput overflowing the parent

![image](https://user-images.githubusercontent.com/11086981/103411843-2acb2280-4b98-11eb-8703-731d3b605089.png)

If we don't give `width=100%` for input, it is will overflow the parent if parent width is smaller than 153px
![image](https://user-images.githubusercontent.com/11086981/103367401-fea59800-4aea-11eb-82ce-ab78a6f9dc85.png)

I think, in order to fix this we wrote this code https://github.com/razorpay/blade/blob/master/src/atoms/TextInput/TextInput.web.js#L435. But its not working

Here we are supposed to make `input` element width=100% instead we are doing it for its parent `InputContainer`

**Comment by haquezameer** [comment]
Can you post a reproducible code in the issue?

From the screenshot, I am not sure if that is blade DS component.
