### ISSUE TITLE
Table row selected state

### ISSUE THREAD

**Issue by AnkitaBagale** [razorpay/blade#2273]
Issue: Table row when clicked, I want to open details view but the row checkbox should not get selected. and Row should be in selected state as details view is open.

> Row should be in selected state as details view is open.

Can we add isSelected prop on row?

> the row checkbox should not get selected

Can we expose events in onClick handlers so that consumer can stop propagation if needed, or is there any way we can provide this experience?

Existing table:
![image](https://github.com/razorpay/blade/assets/69760792/9535fbca-2b45-495b-90ac-8e678680f993)

Blade table:

![image (1)](https://github.com/razorpay/blade/assets/69760792/8a67191a-faeb-440c-bdc2-740f729fc35c)

**Comment by anuraghazra** [comment]
This is fixed in #2283 

We've added a new prop called `multiSelectTrigger` which you can set to `checkbox` to achieve the desired behaviour.
