### ISSUE TITLE
For table (with paginationType="server") footer, background color is missing.

### ISSUE THREAD

**Issue by AnkitaBagale** [razorpay/blade#2279]
For table (with paginationType="server") footer, background color is missing.

Actual - 
<img width="1640" alt="image" src="https://github.com/razorpay/blade/assets/69760792/bdd368d4-af2b-4293-b696-599f4dc02e4c">

Expected - 
<img width="1653" alt="image" src="https://github.com/razorpay/blade/assets/69760792/14fe217d-e664-4e58-854a-a05a2869b1e0">

**Comment by Sumitmaithani** [comment]
Hi, please can I work on this issue?

**Comment by snitin315** [comment]
@Sumitmaithani Yes.
