### ISSUE TITLE
Radio button is distorted on longer text

### ISSUE THREAD

**Issue by victorakaps** [razorpay/blade#2310]
when radio option text is longer and wrapping into multiple lines, the option button gets shrinked because it doesn't have minimum width.
<img width="710" alt="Screenshot 2024-07-15 at 12 37 45 PM" src="https://github.com/user-attachments/assets/fe0a9fe0-a92a-43bc-8193-28684526fe7b">

demo: https://stackblitz.com/edit/xzmzkj-fcdcnx?file=App.tsx

issue thread: https://razorpay.slack.com/archives/C079MAT0UQG/p1721026966027969?thread_ts=1721022550.243779&cid=C079MAT0UQG

**Comment by Sumitmaithani** [comment]
Is anyone working on this? If not can I pick this up.

**Comment by saurabhdaware** [comment]
Yes sure @Sumitmaithani , you can go ahead. Thanks!
