### ISSUE TITLE
Accordion heading title spills over.

### ISSUE THREAD

**Issue by krishnaacc123** [razorpay/blade#2334]
Encountered an issue where title of accordion header spills over when length is more than width available.  Also causing spill of trailing content and arrow.

![Screenshot 2024-08-20 at 2 24 45 PM](https://github.com/user-attachments/assets/09bec183-2d7e-4e45-aa5d-65ab1a41b26d)

**Comment by saurabhdaware** [comment]
Might have to add breakWord="all" in BaseHeader. Keeping it open for anyone who wants to contribute

**Comment by Sumitmaithani** [comment]
Hi @saurabhdaware, just saw this. Can I take it up?

**Comment by saurabhdaware** [comment]
sure @Sumitmaithani . Let us know if you need any help
