### ISSUE TITLE
AccordionItemHeader slot not taking full width

### ISSUE THREAD

**Issue by Akshay090** [razorpay/blade#2359]
Issue Summary:
The AccordionItemHeader slot element does not take the full width, even when a width of 100% is applied.

Description:
This issue appears to be caused by the Box component that wraps the slot element, which does not have the appropriate styles. The wrapping Box component may be redundant. I have removed it, and the base accordion seems to be working fine without it.

PR Link: https://github.com/razorpay/blade/pull/2357/

Link to Example reproducing issue : https://stackblitz.com/edit/fu9qww

**Comment by anuraghazra** [comment]
Fixed in https://github.com/razorpay/blade/releases/tag/%40razorpay%2Fblade%4011.30.1
