### ISSUE TITLE
Fix: Mobile View in Intro Page of https://blade.razorpay.com/?path=/docs/guides-intro--docs

### ISSUE THREAD

**Issue by sarthak-kumar-shailendra** [razorpay/blade#2380]
When we view the intro page https://blade.razorpay.com/?path=/docs/guides-intro--docs, the screen looks odd.
<img width="324" alt="Screenshot 2024-10-17 at 12 21 27 AM" src="https://github.com/user-attachments/assets/3e689d47-145f-4406-83aa-8703423d654f">
<img width="326" alt="Screenshot 2024-10-17 at 12 21 41 AM" src="https://github.com/user-attachments/assets/cf36adbf-c24e-4d74-a720-9c531daa1461">

It looks better like this
<img width="321" alt="Screenshot 2024-10-17 at 12 22 07 AM" src="https://github.com/user-attachments/assets/ea4612db-cd39-4241-9428-5436c5818304">

**Comment by RajdeepDey010** [comment]
Hi @sarthak-kumar-shailendra I would like to work on this task.
