### ISSUE TITLE
[Blade/New]: consider runtime checks and showing logs only in dev mode

### ISSUE THREAD

**Issue by kamleshchandnani** [razorpay/blade#272]
We need create a way to strip off development logs while building the library. This will also save us tons on bundlesize

**Comment by divyanshu013** [comment]
Now that we're also adding lot of runtime checks, this can be quite useful

**Comment by divyanshu013** [comment]
We're seeing quite some occurrences ☝️, should we prioritize this sometime soon @kamleshchandnani @nashcheez ?

**Comment by nashcheez** [comment]
As the library becomes mature, this is pretty important. Let's take a task next sprint.

**Comment by divyanshu013** [comment]
Another usecase of making these dev only. Sometimes users dynamically determine the props based on some API responses, etc. Say if they forget to test out a particular combination on development some end users might end up running into those in production 💥

**Comment by chaitanyadeorukhkar** [comment]
Have we already done this in some of the mentioned PRs @divyanshu013 ?

**Comment by divyanshu013** [comment]
No, we haven't yet.
