### ISSUE TITLE
[Blade/New] Install fails on npm 7

### ISSUE THREAD

**Issue by pronav** [razorpay/blade#332]
Installing blade fails for all versions on npm 7. Problem is with peerDependencies which are now installable by default, and there's a conflict because of the strict versions present in package.json

Another issue is downloading of `react-native` in web projects and vice-versa, causing more time to download in all builds.

Possible solution: empty peerDependencies object in package.json

**Comment by kamleshchandnani** [comment]
The `peerDependencies` are already following semver. Why is it causing an issue? What version of react do you have in your project?
```
"peerDependencies": {
    "@babel/runtime": "^7.14.6",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-native": "^0.64.0"
  },
```

>Another issue is downloading of react-native in web projects and vice-versa, causing more time to download in all builds.

Only the installation should take the time that too if you don't have lock files(i.e on fresh installs). Otherwise builds shouldn't take time since web doesn't has to do anything with react native. Let me know if you have more details on this?

**Comment by pronav** [comment]
Fails without any react too:
```
{"dependencies":{"@razorpay/blade":"^0.0.7"}}
```
^This in package.json in an empty folder also fails. This is happening for all 4 developers who've tried on mac & linux.


Error clearly indicates it's about version conflict. Running
```
npm view react-native peerDependencies
```
tells that react-native depends on React "17.0.1" strict, which collides with "17.0.2" and above in blade's dependecies.

You can also use new field peerDependenciesMeta in package.json to avoid pacakge download

**Comment by pronav** [comment]
React 17.0.1 fails with blade and 17.0.2 fails with RN. Any other version fails with both

**Comment by kamleshchandnani** [comment]
Can you try now with the latest version of blade i.e `0.1.6`. I did try with npm v8 and it installed dependencies without any errors.

**Comment by pronav** [comment]
Sure @kamleshchandnani, will retry.
