### ISSUE TITLE
[Blade/New]: Form component inspired by remix

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#395]
It will be cool to have a `<Form>` component like Remix in blade.

Remix Form Docs: https://remix.run/docs/en/v1/guides/data-writes

Example API

```js
import { Form, Input, Button } from '@razorpay/blade';

// ...

<Form method="post" action="/user/signin" onResponse={(res) => {/* do something with response */ }}>
  <Input name="email" />
  <Input name="password" />
  <Button type="submit">Login</Button>
</Form>
```

This will reduce the JavaScript the consumer has to write to build forms.

**Comment by divyanshu013** [comment]
This would be also dependent on the action endpoint being able to parse form data - and dependent on the server (remix has concept of actions and loaders which help to an extent). I think instead, we should identify UI layer specific takeaways (if any) from remix forms and evaluate if those can be added.

**Comment by saurabhdaware** [comment]
This is possible natively in React using React Server Component's server actions. Don't think so this is in scope of Blade to solve.

https://nextjs.org/docs/app/api-reference/functions/server-actions#with-client-components
