### ISSUE TITLE
[Blade/Old]:  🐛 bug(Button):  Secondary variant background color is too dark

### ISSUE THREAD

**Issue by avinashdvv** [razorpay/blade#398]
Design:
<img width="346" alt="Screenshot 2021-12-28 at 1 29 09 PM" src="https://user-images.githubusercontent.com/11086981/147542965-684d9d35-936a-441d-9273-20a7e422f3d0.png">

On Development
<img width="324" alt="Screenshot 2021-12-28 at 1 29 18 PM" src="https://user-images.githubusercontent.com/11086981/147542983-5d567dd1-ff0b-4b72-986a-c7f39879fa4f.png">
```
<Button
    block
    type="button"
    variant="secondary"
    variantColor="negative.960"
    size="medium"
    onClick={handleCancelSubscription}
    children={`Cancel ${!isMobile ? 'Subscription' : ''}`}
  />
```

**Comment by chaitanyadeorukhkar** [comment]
Can you raise a PR for this @avinashdvv ?

**Comment by tapan-flyfin** [comment]
@chaitanyadeorukhkar do you guys accept open source contributions?
I can raise a PR for this.

**Comment by divyanshu013** [comment]
Closing this since, blade-old is in maintenance only mode. We recommend using Button from blade-new now. Please open a fresh issue for blade-new in case it happens.
