### ISSUE TITLE
Remove `gap` prop from `Box` component and its usage across components & stories

### ISSUE THREAD

**Issue by chaitanyadeorukhkar** [razorpay/blade#603]
Since there is no support for `gap` on React Native yet, adding support for `gap` on `Box` would lead to UI breakage on native components. We have already used `gap` with `Box` at multiple places and we need to remove those instances and replace them with other appropriate spacings.

**Comment by chaitanyadeorukhkar** [comment]
@anuraghazra do you want to take this up since it could have some impact on Checkbox?

**Comment by anuraghazra** [comment]
Yes I'll fix this.

**Comment by anuraghazra** [comment]
Fixed in #758
