### ISSUE TITLE
Add icons grid story

### ISSUE THREAD

**Issue by divyanshu013** [razorpay/blade#669]
Add a story to showcase all icons so it makes it easier to identify which already exist

**Comment by YashasviChaurasia** [comment]
@chaitanyadeorukhkar @divyanshu013 I would like to work on this issue.
Could you please assign it to me, Thank you.

**Comment by YashasviChaurasia** [comment]
@divyanshu013 Can this issue be marked for hacktoberfest?

**Comment by divyanshu013** [comment]
Yeah, we can add a `hacktoberfest-accepted` label to the PR

**Comment by YashasviChaurasia** [comment]
Could you please describe the issue a little bit and how should I implement it.
Thank you

**Comment by chaitanyadeorukhkar** [comment]
@YashasviChaurasia you can learn more about Storybook & what a [story is here](https://storybook.js.org/docs/react/get-started/introduction). 

In this issue we want to add a grid of icons to showcase the available icons on blade. Something [similar to this](https://chakra-ui.netlify.app/?path=/story/icons--default).

**Comment by divyanshu013** [comment]
You may check `packages/blade/src/components/Icons/Icons.stories.tsx` for what we've on the existing stories. You'll likely need to add a story that adds support for a grid layout so we can see all icons at a glance. Please refer to the contributing guidelines at the repo root for any setup related instructions.

**Comment by harshcut** [comment]
This is what I came up with. When `icon` is set to `undefined` it shows all available icons with their respective names. To see individual icon, select option can be used.

The icons don't properly fit in a grid, as some of them have large `iconName`.

https://user-images.githubusercontent.com/86551248/201513613-766c88d3-0e89-40ff-a118-103ebad44434.mp4

**Comment by harshcut** [comment]
> Could you try to use ellipsis and truncate the text if it overflows?

I couldn't figure out how to use the `css` property on the `Text` component. If you could show an implementation of it, would be helpful. Otherwise, the `small` element works.

![blade-icon-grid](https://user-images.githubusercontent.com/86551248/201680702-be5501df-2931-4347-a9b4-404030743ac2.png)

**Comment by kamleshchandnani** [comment]
@YashasviChaurasia can you try setting `truncateAfterLines: 1` on the text?
