### ISSUE TITLE
Consider adding exports last eslint rule

### ISSUE THREAD

**Issue by divyanshu013** [razorpay/blade#674]
Let's export at the end, easier to track what we are exporting.

_Originally posted by @anuraghazra in https://github.com/razorpay/blade/pull/666#discussion_r955700599_

- [Ref](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/exports-last.md)

**Comment by jainpawan21** [comment]
Hi @divyanshu013, I would like to work on this.
Can you please assign this to me?

**Comment by divyanshu013** [comment]
This is pending some discussions, please hold on.

**Comment by divyanshu013** [comment]
Closing since we don't wan to enforce this at the moment.
