### ISSUE TITLE
plugin dts: syntax not yet supported error in build

### ISSUE THREAD

**Issue by kamleshchandnani** [razorpay/blade#701]
**Issue:** aliased imports from `~components/Form` breaks the type generation

**Workaround(not ideal but unblocking release for now):** replace alias imports with relative imports `~components/Form` ➡️ `../../Form`

**Ideal solution:** the alias imports shall work too

Temporary workaround in https://github.com/razorpay/blade/pull/700

**Comment by divyanshu013** [comment]
For now I think we should add a linting rule to disallow the problematic import /cc @anuraghazra

**Comment by anuraghazra** [comment]
Faced this bug while working on BottomSheet too. 

I think I got the pattern to fix this bug. 

While building rollup will tell you have some random component syntax is broken, that means you are importing that component's type via the aliased import.

**Comment by anuraghazra** [comment]
rollup-plugin-dts is failing in weird places & throwing syntax errors, wastes a lot of time trying to pin point the error. 

For example: 

This throws syntax error:
```jsx
<GestureHandlerRootView style={{ flex: 1 }}>
```
But this doesnt:
```jsx
<GestureHandlerRootView style={gestureHandlerStyle}>
```

**We should consider alternatives like [rollup-plugin-ts](https://github.com/wessberg/rollup-plugin-ts)**

**Comment by saurabhdaware** [comment]
Also faced this while refactoring docs. Went on my own exploration unaware of this issue lol. We should definitely pick this soon 😭

**Comment by divyanshu013** [comment]
No. of hours wasted on this issue += 2

It also throws error when you try to do `import { X as Y }` and then trying to export the same module

**Comment by chaitanyadeorukhkar** [comment]
Number of hours wasted on this issue += 2 😭 

It also throws error when you try to import from the `src/components/index.js` file which re-exports all our components. Most of the times, this import is done unintentionally by vscode IntelliSense. Ref commit: https://github.com/razorpay/blade/pull/1258/commits/083d4c13da44e3bc6bfe260a4f74bb10bdfa294d

<img width="1384" alt="Screenshot 2023-06-27 at 12 34 44 PM" src="https://github.com/razorpay/blade/assets/24487274/7971f0c3-2a96-47fa-a5e8-6a33892a6dc7">

**Comment by anuraghazra** [comment]
Number of hours wasted += 2

I had this code which was breaking: 

```jsx
const _BaseBox = React.forwardRef((props, ref) => {
  const { theme } = useTheme();
  const shadow = (getElevationValue(props.elevation, theme) as unknown) as ElevationStyles;

  return (
    <StyledBaseBox ref={ref} {...props} style={shadow ? [shadow, props.style] : props.style} />
  );
}) as StyledComponent<typeof View, DefaultTheme, BaseBoxProps>;

const BaseBox = assignWithoutSideEffects(_BaseBox, { displayName: 'BaseBox' });
```

Had to change this to:

```jsx
const _BaseBox = (props, ref): React.ReactElement => {
  const { theme } = useTheme();
  const shadow = (getElevationValue(props.elevation, theme) as unknown) as ElevationStyles;
  return (
    <StyledBaseBox ref={ref} {...props} style={shadow ? [shadow, props.style] : props.style} />
  );
};

const BaseBox = assignWithoutSideEffects(React.forwardRef(_BaseBox), {
  displayName: 'BaseBox',
}) as StyledComponent<typeof View, DefaultTheme, BaseBoxProps>;
```
