### ISSUE TITLE
Alerts: Allow `SecondaryAction` only when `PrimaryAction` is defined

### ISSUE THREAD

**Issue by kamleshchandnani** [razorpay/blade#725]
Right now we don't throw any error if the consumers passes `SecondaryAction` without `PrimaryAction` we want to restrict this behaviour. We can't do it with TS but we shall add it as a runtime check.

**Comment by rksingh2001** [comment]
I would like to take up this issue.

**Comment by shivam1646** [comment]
Hi @divyanshu013 @kamleshchandnani 
So basically the `SecondaryAction` should appear only if `PrimaryAction` is defined, right?

something like this
<img width="851" alt="Screenshot 2022-10-20 at 4 28 38 PM" src="https://user-images.githubusercontent.com/50290814/196931585-dc02ff2a-a4a1-4e9d-bdeb-056ccd491934.png">

I'd be happy to open a PR if this looks like a possible fix.

**Comment by jainpawan21** [comment]
> Hi @divyanshu013 @kamleshchandnani So basically the `SecondaryAction` should appear only if `PrimaryAction` is defined, right?
> 
> something like this <img alt="Screenshot 2022-10-20 at 4 28 38 PM" width="851" src="https://user-images.githubusercontent.com/50290814/196931585-dc02ff2a-a4a1-4e9d-bdeb-056ccd491934.png">
> 
> I'd be happy to open a PR if this looks like a possible fix.

As per issue description, An error should be thrown in that case.
In your implementation only null will return.

**Comment by kamleshchandnani** [comment]
> > Hi @divyanshu013 @kamleshchandnani So basically the `SecondaryAction` should appear only if `PrimaryAction` is defined, right?
> > something like this <img alt="Screenshot 2022-10-20 at 4 28 38 PM" width="851" src="https://user-images.githubusercontent.com/50290814/196931585-dc02ff2a-a4a1-4e9d-bdeb-056ccd491934.png">
> > I'd be happy to open a PR if this looks like a possible fix.
> 
> As per issue description, An error should be thrown in that case. In your implementation only null will return.

Rightly mentioned. we don't want to return null, rather we want to throw an error because we want to prevent people from passing the incorrect dependent props.

**Comment by shivam1646** [comment]
Hi @kamleshchandnani thanks for the input. I have opened a PR to address this issue. Could you please take a look when you have some time?
