### ISSUE TITLE
Type="button" prop not present for Link button variant

### ISSUE THREAD

**Issue by PranjalMaithani** [razorpay/blade#737]
When using Link component with button variant, I cannot pass `type="button"` to it, unlike the Button component. This is causing unexpected behaviour when using Link button variant inside forms.

**Comment by divyanshu013** [comment]
Can you share a sample code snippet with expected and current behavior please?

**Comment by PranjalMaithani** [comment]
Sample snippet
```jsx
 const handleFormSubmit = (e) => {
    e.preventDefault();
    console.log('Handle Submit called');
  };

  const handleChangePhoneNumber = () => {
    console.log('change phone number called');
  };

  return (
    <form onSubmit={handleFormSubmit}>
      <Link variant="button" onClick={handleChangePhoneNumber}>
        Change phone number
      </Link>
      <div style={{ display: 'block' }}>
        <label for="otp">OTP</label>
        <input name="otp" />
      </div>
      <Button type="submit">SUBMIT</Button>
    </form>
  );
```

This has just console logs but in the actual scenario the Change Phone number CTA is taking the user to a different page

https://user-images.githubusercontent.com/75153839/195780073-33aadc3a-cef0-4cb7-bb4d-bbe61020af89.mov

Have raised a [PR here](https://github.com/razorpay/blade/pull/746)

**Comment by PranjalMaithani** [comment]
Closing this as the PR for this has been merged
