### ISSUE TITLE
This package might break when `gap` is added to React Native

### ISSUE THREAD

**Issue by jacobp100** [razorpay/blade#771]
Please read issues from [here](https://github.com/facebook/react-native/pull/34974#issuecomment-1279447682)

The offending code is [here](https://github.com/razorpay/blade/blob/b48c385c42df45cfb65ddd364702970222019101/packages/blade/src/components/Box/Box.native.tsx#L5) - the `gap` property will be passed down to the `View` component

**Comment by chaitanyadeorukhkar** [comment]
There is an existing issue regarding this [here](https://github.com/razorpay/blade/issues/603). We're actively not using `gap` anymore in our styles and now we just need to remove it from places where it is used. Closing this as a duplicate for https://github.com/razorpay/blade/issues/603
