### ISSUE TITLE
[Text/react]: Multiline Truncate

### ISSUE THREAD

**Issue by kamleshchandnani** [razorpay/blade#78]
Following are the issues with the Text truncate functionality on web.

1. Issues when `maxLines` set to 2 👇 

<img width="192" alt="Screenshot 2020-03-23 at 3 12 25 PM" src="https://user-images.githubusercontent.com/11384858/77303385-e7927800-6d18-11ea-80ee-f8e4ac245cfa.png">

2. Issues when `maxLines` set to 5 👇. Basically if lines have less text then the available width in the maxLines the issue occurs.  

<img width="1200" alt="Screenshot 2020-03-23 at 3 12 46 PM" src="https://user-images.githubusercontent.com/11384858/77303424-f416d080-6d18-11ea-85fb-10bad5448624.png">

3. Issue when the `...` is rendered sometimes it overlaps with the text

**Comment by divyanshu013** [comment]
Closing since this was related to https://github.com/razorpay/blade-old
