### ISSUE TITLE
Heading, Text components don't inherit center alignment

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#785]
Reproduction: https://codesandbox.io/s/center-align-not-working-blade-l1sqi3?file=/src/App.tsx

I added the components inside center aligned div. It gets applied to some component but doesn't work on some components 🤔 

<img width="563" alt="image" src="https://user-images.githubusercontent.com/30949385/198243415-7e260bb2-a656-4a5b-88cc-208460fdeaf8.png">

**Comment by saurabhdaware** [comment]
> found the issue. we extend basetext in typography elements and the default value if not passed is left so the parent’s thing is getting overriden by the BaseText when rendered
>
> ~ @kamleshchandnani

**Comment by kamleshchandnani** [comment]
we shall remove the default value for `textAlign` and let it be undefined and that shall fix it.
