### ISSUE TITLE
OTP Field is accepting text charcters

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#786]
Repro: https://codesandbox.io/s/otp-accepts-text-blade-o9xp48?file=/src/App.tsx

OTPInput is also accepting text characters as input. Ideally we should set `type="number"` on the input fields to not allow these characters.

<img width="341" alt="image" src="https://user-images.githubusercontent.com/30949385/198252633-49cf5d5a-e32c-4d8e-8932-8b7621155b3f.png">

**Comment by saurabhdaware** [comment]
Related Slack Thread: https://razorpay.slack.com/archives/CMQ3RBHEU/p1669193586528849?thread_ts=1665483409.203739&cid=CMQ3RBHEU

@chaitanyadeorukhkar

**Comment by divyanshu013** [comment]
We can't rely simply on type number because of how it would also affect the UI, so it likely needs to be done with validation (maybe regex check)

**Comment by divyanshu013** [comment]
On similar pretext we might want to consider a validation for textinput with number type

**Comment by divyanshu013** [comment]
Okay, let's revisit if needed
