### ISSUE TITLE
[Badge]: stories does not show icons

### ISSUE THREAD

**Issue by shivam1646** [razorpay/blade#789]
###  **Steps to reproduce**

1. Go to components -> Badge
2. Select Small Size
3. Go to stories tab
4. From controls, try selecting an icon

### Expected Behaviour
The selected icon should show up on the left side of the text inside the badge.

### Actual behaviour
Icon does not show up inside the badge.

<img width="1431" alt="Screenshot 2022-10-27 at 10 21 01 PM" src="https://user-images.githubusercontent.com/50290814/198351956-51ca51b8-bd05-4619-aedb-a613818306d5.png">

**Note**: Same behaviour for `Medium Size`, `With Icon` and `Bold Font` stories.

**Comment by saurabhdaware** [comment]
<img width="760" alt="image" src="https://user-images.githubusercontent.com/30949385/198504653-2bb59e13-613a-4a7e-99bd-05c52bddded6.png">

I can see icons in the master link. Is it happening in any particular browser or device?

**Comment by saurabhdaware** [comment]
Ohhhh understood. You meant in controls from other stories? yup makes sense. We don't usually use that though and expect them to be static variants but the PR looks good to me 🎉
