### ISSUE TITLE
Color Scheme doesn't change with state change

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#798]
Repro: https://codesandbox.io/s/colorscheme-state-change-bug-eykg2f?file=/src/App.tsx

I created an example which has button which changes the state between `light` and `dark` and I am setting that value in `colorScheme` property in `BladeProvider`.

Ideally I would assume the colorScheme to change with that state change but it is not happening.

**Comment by kamleshchandnani** [comment]
weird because the same setup works on [storybook](https://master--61c19ee8d3d282003ac1d81c.chromatic.com/?path=/docs/components-typography-text--text) 🤔

**Comment by saurabhdaware** [comment]
Oops understood. So the `colorScheme={}` that we pass from `BladeProvider` is used as an initial colorScheme value and not the currentColorScheme value.

But we do seem to already have `setColorScheme` function on blade context that can be used for this.

Using the `setColorScheme` fixed this.

```jsx
function SchemeChanger() {
  const { theme, setColorScheme, colorScheme } = useTheme();

  const toggleColorScheme = () => {
    setColorScheme(colorScheme === "light" ? "dark" : "light");
  };

  return (
    <div
      style={{
        backgroundColor: theme.colors.surface.background.level1.lowContrast
      }}
    >
      <Text>This text should ideally toggle between white and dark color</Text>
      <Button variant="secondary" onClick={toggleColorScheme}>
        Toggle Color Scheme
      </Button>
    </div>
  );
}
```

https://codesandbox.io/s/colorscheme-state-change-bug-fixed-leunzh?file=/src/App.tsx

I don't feel we need to change anything here. Just that we should document this somewhere.

While working on recipes task, I'll also create a recipe for colorScheme changes.

Will keep this open and close it work recipe task.

**Comment by saurabhdaware** [comment]
Closing this as the implementation is covered in dashboard recipe
