### ISSUE TITLE
Should subheading render as h6?

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#812]
```html
<Title>Main Heading</Title>
<Heading variant="subheading">Something something</Heading>
<Text>Hi there!!</Text>
```

will render as 

```html
<h1>Main Heading</h1>
<h6>Something something</h6>
<p>Hi there!!</p>
```

is this expected semantics for accessibility? 🤔 shouldn't subheading not be an `h*` tag?

<img width="814" alt="image" src="https://user-images.githubusercontent.com/30949385/199714631-059a9bfc-a2cf-4741-8433-18a7e36fd9fc.png">

// cc @anuraghazra

**Comment by divyanshu013** [comment]
MDN recommends [not skipping heading levels](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#usage_notes) so we might need to revisit later. Maybe an `as` prop support?

**Comment by saurabhdaware** [comment]
React Docs has one nice approach in their example where they create `Section` component and based on the nesting of Section, they decide heading level.

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/30949385/236428384-7346c6dd-74c7-4c83-9097-c736e7d10935.png">

https://react.dev/reference/react/useContext#examples

**Comment by divyanshu013** [comment]
Not sure if automatically determining the h level is good idea but the approach is nice _(could probably be utilized for certain validations if needed)_

**Comment by divyanshu013** [comment]
Discovered another possible usecase of `<Heading as="span">` while working on Accordion:

> need to render a heading inside a button element (accordion header) but apparently heading inside button is invalid (but button inside heading is valid)

![image](https://github.com/razorpay/blade/assets/6682655/3ebf3f62-fd56-4f02-aedd-c7495cf89e8c)

**Comment by cseas** [comment]
All Heading and Title components should support the `"as"` prop with at least h1 to h4.

Posting some examples of heading hierarchy violations from recent designs:

<img width="1220" alt="Screenshot 2023-06-12 at 1 38 10 AM" src="https://github.com/razorpay/blade/assets/29686866/56a7845c-a033-4c17-b347-e2eaa6c1714e">

<img width="837" alt="Screenshot 2023-06-12 at 1 38 50 AM" src="https://github.com/razorpay/blade/assets/29686866/9bd2e539-5064-45f8-81e8-9e1955728487">

The devs are helpless right now in fixing these issues. Please add support for `as` prop to both Heading and Title on high priority. This issue has been open for too long with no conclusion.

**Comment by anuraghazra** [comment]
Fixed in https://github.com/razorpay/blade/pull/1321

Added as support, and now we render subheadings as `p` to make sure logical heading order isn't broken by it.
