### ISSUE TITLE
Minor grammatical error in Alert.tsx

### ISSUE THREAD

**Issue by FrozenHearth** [razorpay/blade#826]
There's a small grammatical error in this file, at line 211:

https://github.com/razorpay/blade/blob/master/packages/blade/src/components/Alert/Alert.tsx#L211

`React Native doesn't has status as role`

This should be, `React Native doesn't have status as role`

**Comment by snitin315** [comment]
It should be `React Native doesn't have status as a role`, PR welcome :)

**Comment by FrozenHearth** [comment]
Yes, your sentence is more grammatically correct. 
So should I create a PR for this or ignore? Thanks.

**Comment by divyanshu013** [comment]
We generally don't hard enforce grammar rules. In this case I think it can be left as it is.

**Comment by FrozenHearth** [comment]
Alright, closing this then.
