### ISSUE TITLE
[TextArea/native] Initial height should be 64px

### ISSUE THREAD

**Issue by chaitanyadeorukhkar** [razorpay/blade#83]
Initial height should be 64px unlike text input which is 36px

**Comment by dhruvdutt** [comment]
Can you add some screenshots as well?

**Comment by adithyaakrishna** [comment]
@chaitanyadeorukhkar Is this issue open? 👀

**Comment by divyanshu013** [comment]
Closing since this was related to https://github.com/razorpay/blade-old
