### ISSUE TITLE
Default validations on Inputs

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#850]
For Inputs like email, password, etc. We can maybe handle validation states from our end only?

E.g. if I type wrong email, the input will show error.

**Comment by saurabhdaware** [comment]
Followup idea to that, `minCharacter` prop on PasswordInput that shows error if typed password is less than that many words

**Comment by divyanshu013** [comment]
Not sure if it would be a good idea. Different products might have different validation needs. I feel it would mean moving some of that business logic as well into Blade 🤔

**Comment by saurabhdaware** [comment]
So things like Email validations might be common for everyone no?

But I guess there are validation libraries out there so people might be using those anyway so should be fine. 

Closing this issue for now, can re-open if someone requests this feature.

**Comment by divyanshu013** [comment]
Email validations might be common but there isn't a standardized email validation check that we could generalize I feel.
