### ISSUE TITLE
Input Focus Color on High Contrast theme is not correctly set

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#855]
## Text Input before focus

<img width="258" alt="image" src="https://user-images.githubusercontent.com/30949385/202970560-f346234c-19cd-48fa-9803-78903a41dca2.png">

## Text Input after focus

<img width="257" alt="image" src="https://user-images.githubusercontent.com/30949385/202970542-472f20f2-1bf9-4b09-a186-bda40d2559cc.png">

Check out searchbar from this example - https://codesandbox.io/s/blade-dashboard-uyijy3?file=/src/Dashboard.tsx

**Comment by saurabhdaware** [comment]
> You mean when we set right?

didn't understand your question 🤔

**Comment by anuraghazra** [comment]
lol sorry used jsx and github didn't rendered it. Updated the comment.

**Comment by saurabhdaware** [comment]
yes when we set colorScheme="light" and use high contrast background with high contrast items on it.

**Comment by saurabhdaware** [comment]
high contrast theme is removed in rebranding so this issue is not valid anymore. rip.
