### ISSUE TITLE
Fonts are not working in Sandpack and CodeSandbox examples

### ISSUE THREAD

**Issue by saurabhdaware** [razorpay/blade#914]
The font in https://blade.razorpay.com/?path=/story/recipes-simple-dashboard--simple-dashboard&globals=measureEnabled:false and other codesandbox and sandpack examples is not Lato.

Looks like some font loading issues

<img width="696" alt="image" src="https://user-images.githubusercontent.com/30949385/207024957-09458807-faad-4f05-8729-76e95a10684a.png">

Reported by @chaitanyadeorukhkar on Slack: https://razorpay.slack.com/archives/G01B3LQ9H0W/p1670831023173849

**Comment by ashutosh887** [comment]
Should I work on this @saurabhdaware 🙂😅
