### ISSUE TITLE
Fix shadow token discrepancies between iOS and Android

### ISSUE THREAD

**Issue by anuraghazra** [razorpay/blade#922]
While working on the Card we noticed a vast difference in shadow opacity between iOS and Android. 

![image](https://user-images.githubusercontent.com/35374649/208673290-a32cf6bd-82ac-4ced-97e4-3b312a25d57f.png)

Slack Thread: https://razorpay.slack.com/archives/G01B3LQ9H0W/p1671538782461409
Original GH Comment: https://github.com/razorpay/blade/pull/896#issuecomment-1359294394

**Comment by divyanshu013** [comment]
Not really a bug, inherent RN thing 😸

**Comment by anuraghazra** [comment]
Right, ideally we need to fix our elevation tokens.

**Comment by divyanshu013** [comment]
Related [shadow / elevation](https://docs.google.com/document/d/1GQEd-1JXFDbv3JsBMB2TgiSn8EJE43Gtm_Xtb_8dn04/edit#heading=h.2dz0hmm0hw6t) explo by @saurav12

**Comment by chaitanyadeorukhkar** [comment]
This is fixed and in a much better state after elevation revamp. Closing it.
