### ISSUE TITLE
Add motion token for `linear` easing

### ISSUE THREAD

**Issue by chaitanyadeorukhkar** [razorpay/blade#924]
We're using `linear` easing with `ProgressBar` component. For now we have hardcoded it but we will need to add this to our tokens since there are use-cases that will come up in the future too for a linear easing.

**Comment by kamleshchandnani** [comment]
do we have use case for this now? if not I'll move this to enhancement and not P1.

**Comment by chaitanyadeorukhkar** [comment]
We are already using linear in a component but haven't seen more use-cases since. We can mark it as enhancement only for now

**Comment by kamleshchandnani** [comment]
I'll close this for now and we can re-open later.
