### ISSUE TITLE
Typography Accessibility issue: Allow controlling rendered element

### ISSUE THREAD

**Issue by cseas** [razorpay/blade#951]
## Problem

The Blade documentation for Typography [Heading][1] states that it should be used for headings of each major section of a page. Semantically it renders as an `<h4>`.

The [Title][2] component on the other hand states that it should be used for landing pages and marketing, with no indication that it should be used on every page where a Heading is. Title renders as `<h1>`, `<h2>`, & `<h3>` based on the text size. Again, the developer has no control over what's rendered here since the size will be decided by the designer.

Not sure what the designer guidelines on using these elements are, but unless every design is using all 3 versions of Title before using Heading, this goes against W3C Accessibility standards for [Headings][3].

For example, the guideline `Make sure that a <h2> is not followed directly by an <h4>` can easily and very likely be violated with the setup Blade has.

## Solution

While it's good that Typography components meant for headings have a default rendered html, this behavior should not be restricted as restricting it does more harm than good in most cases. The developer should be able to control the semantic element being rendered.

If a design only has a Title and Headings, the semantics should be `h1` and `h2`, not `h2` and `h4`.

[1]: https://blade.razorpay.com/?path=/docs/components-typography-heading--heading&globals=measureEnabled:false
[2]: https://blade.razorpay.com/?path=/docs/components-typography-title--title
[3]: https://www.w3.org/WAI/tutorials/page-structure/headings/

**Comment by divyanshu013** [comment]
Related #812

**Comment by anuraghazra** [comment]
Fixed in https://github.com/razorpay/blade/pull/1321
