### ISSUE TITLE
Mark react-native as an optional dependency

### ISSUE THREAD

**Issue by cseas** [razorpay/blade#957]
## Problem

This is a follow-up for #954 

After the fix deployed from #955, the dependency resolution for react v18 in npm v8 is working correctly. 🎉 

However, the npm install still fails because `react-native` is marked as a peerDependency which in turn depends on `react@"17.0.2"`. Please see the below log for the full error:

```sh
npm i @razorpay/blade@5.5.1
```

> npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!   peer react@">=17" from @razorpay/blade@5.5.1
npm ERR!   node_modules/@razorpay/blade
npm ERR!     @razorpay/blade@"5.5.1" from the root project
npm ERR!   1 more (react-dom)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.66.5
npm ERR! node_modules/react-native
npm ERR!   peer react-native@"^0.66.5" from @razorpay/blade@5.5.1
npm ERR!   node_modules/@razorpay/blade
npm ERR!     @razorpay/blade@"5.5.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

## Solution

I feel this is largely a problem created by the react-native team since they specify exact version of react in peerDependencies instead of a range. And the error can be fixed upstream from react-native.

However, on blade's end, requiring a consumer project (that's only building for web) to install react-native isn't right either. We can fix this error from blade too by marking the react-native dependency as optional in [peerDependenciesMeta][1]. This would make sure a consumer project installs the right version of react-native if they want to, but the install would be optional.

Happy to send a PR if this makes sense.

[1]: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta

**Comment by kamleshchandnani** [comment]
the issue occurs because of the automatic installation of `peerDependencies` which was introduced from npm v7+.

From the [docs](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependencies)
> In npm versions 3 through 6, peerDependencies were not automatically installed, and would raise a warning if an invalid version of the peer dependency was found in the tree. As of npm v7, peerDependencies are installed by default.

Marking the `peerDependencies` optional via `peerDependenciesMeta` is only making things work for web projects which is only one part of the solution to the problem and not the ideal fix.

Rather, to make it work more logically I would recommend using the `omit = peer` under `.npmrc` which will not install `perrDependencies` by default. [More details in the docs](https://docs.npmjs.com/cli/v8/using-npm/config#omit)

**Comment by cseas** [comment]
Just tried, `omit="peer"` doesn't fix/change the error. The below flags do:

- legacy-peer-deps=true (shows no warnings/errors)
- force=true (shows warning for the react-native dependency but installs successfully anyway)

However, the above flags practically ignore peerDependencies. And for all packages being installed, not just Blade so they shouldn't be recommended to users.

If we're sure react-native is a necessary for web projects too, then there are 2 approaches to fix the error:
1. Update react-native to latest version. This will update react-native's peerDependencies to react v18. But this will break the install for react v17 so probably a breaking change.
2. Take it up with the react-native team to support both react 17 & 18 in peerDependencies.

**Comment by kamleshchandnani** [comment]
haven't used npm v7+ hence asking - what happens when you run `npm install @razorpay/blade` in a react project where react version 17 is already isntalled and where the react version 18 is already installed? does npm downloads again?

**Comment by cseas** [comment]
Didn't get the question. The error is coming up for a project with react v18 installed.

A project with react v17.0.2 wouldn't throw any error since `blade` and `react-native` are both happy with that version. react-native might error out for other version of react v17 since it has pinned the exact version in peerDependencies but if it happens, that's a bug for react-native team to solve not related to Blade.

If you wanna reproduce the error or play around with fixes, here's a minimal repo: https://github.com/cseas/repro
Running `npm i @razorpay/blade` with npm 7+ in this repo will reproduce the error.

> **Note**
> Temporary fix:
We could add in the docs that web-only projects using npm can install with the force flag: `npm i @razorpay/blade --force`. Installing this way only ignores Blade's peerDeps while still respecting peerDeps of other packages being installed by the user.

**Comment by kamleshchandnani** [comment]
what happens when you already have a project with React v17 and then you install blade in that project but blade has a peerdependency on react v18 which means now you will have two versions of react in the same project?

**Comment by cseas** [comment]
## Current behaviour

> 1. Project with react v17

Blade installs fine in a project with react v17. Since v17.0.2 satisfies both the react and react-native peerDependencies. 

The only version of React installed in node_modules is v17.
react-native is also installed in node_modules.

> 2. Project with react v18 (Bug)

Regular install will fail with an error because react-native requires react v17. We need to use the `--force` or `--legacy-peer-deps` flags which will ignore the peerDependencies declared by Blade.

The only version of react installed in node_modules will remain v18.
react-native is not installed in node_modules because of the flag used.

## Expected behaviour

> Fix 1: Mark react-native dependency as optional

This will ignore the react-native peerDependencies declaration for projects that don't have react-native in their `package.json`. Both react v17 and react v18 web projects will be able to install Blade because npm will not try to install react-native now.

> Alternate Fix 2: Update the react-native version of Blade

This will still install react-native in node_modules.
But it will reverse the current behaviour. Now projects with react v17 will need the `legacy-peer-deps` flag instead of projects with react v18.

**Comment by kamleshchandnani** [comment]
Sure. I think then marking react-native as optional seems okay to me till we upgrade to have react-native v0.71 which has react 18 as peerDependency set
