### ISSUE TITLE
Storybook link on Google search results is wrong

### ISSUE THREAD

**Issue by cseas** [razorpay/blade#962]
https://blade.razorpay.com/iframe.html?id=guides-intro--page&args=&viewMode=story

<img width="700" alt="Screenshot 2023-01-09 at 1 36 52 PM" src="https://user-images.githubusercontent.com/29686866/212848859-e5d19b99-d887-4b4d-9547-f0cacdeeceba.png">

Refer [Slack discussion][1]

[1]: https://razorpay.slack.com/archives/C01H13RTF8V/p1673251722103579

**Comment by divyanshu013** [comment]
Not sure how we can fix this with storybook 🤔

**Comment by divyanshu013** [comment]
Closing this for now, not sure how we can resolve this from our end unfortunately. Happy to reopen if there is a way to solve this.
